### ISSUE TITLE
Fix all the event-number instances in doEvent.as/eventParser.as/combat.as etc...

### ISSUE THREAD

**Issue by herp-a-derp** [herp-a-derp/Corruption-of-Champions#29]
Basically, a LOT of the events rely on having a case of `doNext(13)` following the event in the `if` `else` statements in `eventParser.as`. 

This causes the event to fail when it's called directly, rather then through `eventParser.as`. 

Basically all these cases of doNext need to be refactored into the function that's actually called in the if statment.

This bug is basically a reminder to Herp-A-Derp to FIX ALL THE THINGS, DAMMIT!

**Comment by Gedan** [comment]
rip in rip coc
