### ISSUE TITLE
Artists for Image Pack

### ISSUE THREAD

**Issue by Fenoxo** [herp-a-derp/Corruption-of-Champions#42]
I have a list of artists that are okay with art usage added to the repo if anyone ever wants to pull some of their stuff for the art-pack.

**Comment by Gedan** [comment]
Probably better to just direct people towards one of the fan image packs hosted on the forum now:

https://fenoxo.com/forum/index.php?/topic/36-hn0s-custom-image-pack-version-5/#comment-182
