### ISSUE TITLE
Sleep with Shylla don't restore fatigue...

### ISSUE THREAD

**Issue by trixymoon** [herp-a-derp/Corruption-of-Champions#440]
file dungeon2Supplimental.as, line 2654
model.time.days++
not restoring fatigue (missing camp.sleepRecovery(false);),

and if i feeded Shylla the day before, i can't found her at bar the next day.

Actually after browsing the code, I understand that the game non update it's state cause is missing the call to goNext method. I gave it a quick read to the function and from what I could understand "goNext" was not meant to be called outside the camp...

Actually the same things happens after "to camp" scene after Sheila Preg Notification (function "normalSheilaPregNotifREPEATEDEDHelpABitchOutTOCAMP"
but in this case the player is in the camp a maybe goNext is usable. (honestly I have not tested it)

potentially whenever, in the code you advance the day and do not call
function goNext, the game state is not updated (pregnancies, addictions, etc.).

Anyway, i get the feeling that you were already aware of this, is a bit too flashy bug, to go unnoticed.

**Comment by Gedan** [comment]
Calling it a write off.
