### ISSUE TITLE
Android Load From File KIA

### ISSUE THREAD

**Issue by CoyoteShadowwolf** [herp-a-derp/Corruption-of-Champions#496]
I tried to load an old old old .sol file from back before the android version broke loading previous saves (shakes fist) and I change the file to .coc and it shows up but clicking the button does nothing, not even locking up the game. It's like dead code, tried on other fresh saves, same result.

**Comment by Gedan** [comment]
I don't have a device that exhibits the issue, and without one I can't really dig into the problem.

**Comment by Gedan** [comment]
See #815
