### ISSUE TITLE
Marble in the morning

### ISSUE THREAD

**Issue by chokie** [herp-a-derp/Corruption-of-Champions#639]
Current patch-update whatever has it where she keeps breastfeeding me or whatever and my corruption goes up to 40 and stops.  I can't do anything when this happens other than close the browser and start the game up again.  I would say it happens about 90% of the time.  Since somehow I messed up the Marble's Milk addiction and got addicted which I don't see how that happened.  I guess if I wasn't addicted this wouldn't be happening?  When I wake up in the morning and gain +2 corruption and get JoJo to remove that or go do something else the game goes back to Marble and the game thinks its still 6am.

**Comment by Fenoxo** [comment]
We really need a save file to look at in order to hunt down problems like these.
