### ISSUE TITLE
Code commenting project

### ISSUE THREAD

**Issue by Mattibun** [herp-a-derp/Corruption-of-Champions#641]
Hello developers,

After playing CoC for some time, I've been thinking of how I could help. Since CoC is heading for completion but demand is still high for changes and expansions, I thought about going through the code and adding more explicit comments. The idea is to help others, like myself, who would want to edit the game later to understand what is going on inside the codebase before they get their hands dirty.

As an example from CoC.as:

// This is the main file for CoC. Everything starts here.

import classes.GlobalFlags.kFLAGS; // Imports the list of flags for the game.
import classes.GlobalFlags.kGAMECLASS; //Imports code to create the base CoC class.
import classes.Scenes.Dungeons.D3.D3; //Imports Dungeon 3 code explicitly (why?)
import classes.CoC_Settings; //Error handling code, looks to be for debugging. Confirm.

Would this be useful?

**Comment by Fenoxo** [comment]
Not really.
