### ISSUE TITLE
Turning Rubi into female removes Training button

### ISSUE THREAD

**Issue by JLDomingo** [herp-a-derp/Corruption-of-Champions#642]
After getting Rubi's affection up to 100%, and after unlocking the training button, I trained Rubi until Orifice Capacity was 74%, then I gave her P. Succubus Milk, she grew a vaj, but I lost the option to train her.

**Comment by Fenoxo** [comment]
Rubi having a pussy shouldn't affect being able to train her.

This is the check for the scene:
if (flags[kFLAGS.RUBI_AFFECTION] >= 75 && rubiCapacity() < player.biggestCockArea() && player.hasCock())

It's likely she got big enough for you, thus removing the scene.
