### ISSUE TITLE
Ember Cum Reduction

### ISSUE THREAD

**Issue by Dragonok** [herp-a-derp/Corruption-of-Champions#646]
When I have sex with Ember for the first time, my cum production decreased from 5843 mL to a measly 145 mL! Even when it's just a simple blowjob, it happens. So sad ; U ; Will you please fix this issue? Thank you for taking your precious time in fixing this issue!

**Comment by Fenoxo** [comment]
Looked at the "get a blowjob from ember" scene. Didn't see anything that would adjust cum amounts.
