### ISSUE TITLE
Marble Left Me Forever!

### ISSUE THREAD

**Issue by Dragonok** [herp-a-derp/Corruption-of-Champions#647]
After I sent Marble to search for her family in the Marble Purification Quest, she never returned even it's been weeks (in the game). Please fix it as soon as possible. Thank you!

**Comment by electrocross** [comment]
I discovered that, if she leaves for her family, and you reload a save (from after she left) before she comes back, she disappears, but this can be avoided by saving as soon as she returns.

**Comment by CalCoast** [comment]
Odd, I experienced something similar. At the end of Urta's Fertility Quest, if you don't let Urta impregnate you, she runs off to go screw Edryn. I chose the latter option. 

Urta didn't come back for 15 days.

**Comment by Ultimaximus** [comment]
@CalCoast I solved that, see issue #818
