### ISSUE TITLE
succubi milk/bust size

### ISSUE THREAD

**Issue by archmancer8** [herp-a-derp/Corruption-of-Champions#650]
succubi milk no longer results occasionally in spontaneous orgasm. Also, bust size will never go beyond "big ZZZ-cup bra" to game-breaking bra.

**Comment by Fenoxo** [comment]
Assuming the former is that your lust isn't actually reduced. The text of the orgasm seems fine. Fixt that.

As far as tits maxxing out at ZZZ - that's fine and dandy.
