### ISSUE TITLE
Unknown event on touching Marae's boobs

### ISSUE THREAD

**Issue by skyace** [herp-a-derp/Corruption-of-Champions#654]
Please report that you had an issue with code: "2075" 
Game version: "0.9.2_mod_1.0.11"

Steps: get into boat, find Marae, touch boobs.

**Comment by Kizuro** [comment]
Congratulations, you've found a bug!
Error: Unknown event!

Please report that you had an issue with code: "2075" 
Game version: "0.9.2_mod_1.0.14" (THIS IS IMPORTANT! Please be sure you include it!) to fake-name on the forums or better yet, file a bug report on github: 
https://github.com/herp-a-derp/Corruption-of-Champions
Please try to include the details of what you were doing when you encountered this bug  to make tracking the issue down easier. Thanks!

**Comment by IndirectOne** [comment]
Again, I'm pretty sure this is a problem with the mod, not the base game. Try the same in 0.9.2 <Not Modded> and it should work just fine.

**Comment by Fenoxo** [comment]
Mod bug reports don't go here.
