### ISSUE TITLE
And more mispells

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#658]
¤Nieves - Mispelling
You grab Nieve around the waist, pulling her close for a kiss. Your tongue explodes (should be explores) into her mouth, as she offers very little resistance. It feels rather like you’re kissing an icecube than a mouth, albeit a soft, fleshy icecube. Your lips tingle from the cold as you break the kiss.

¤Gargoyle - Is the demon a he or a she?
She continues, “After Master had lived here two, maybe three years – all the while experimenting on and manipulating the monsters that came near – we were eventually visited by a demon. Not an imp or minor monster, but a true demon of great power. An omnibus who fancied herself a master of magic, who’d heard of Master’s skill through the mangled imps that managed to crawl away after Master had had her fun. He challenged her to a duel for her magic and her body. Fueled by hubris, she accepted.”

¤Urta (Romance & Sex > Tease) - There is a 'be' missing.
You smirk back at her. Surely, you tell her, that doesn’t mean she doesn’t have the occasional fantasy about what she’d like to do with a willing partner. At this, Urta blushes, and you press on mercilessly. She said that she always liked males, but what does she like best about them? Does she like the idea of some handsome man sinking his cock into her needy pussy, filling her tightly with his own symbol of masculinity and fucking her? Does she want to be fucked soft and slow, made to feel like a woman in every way? Or does she want to (right here) pounded hard and raw; brutal, wild sex to make her scream her pleasure until the roof rattles from the sound of her ecstasy? Or is it the idea of penetrating men that she likes - the image of taking some pretty little boy and having him meekly suck on her long, hot, throbbing horse-cock, or pushing over a man and making him moan and whine and claw at the sheets while she relentlessly pushes herself ever deeper into his back passage, sinking herself in to the hilt in his bowels?

**Comment by Zeikfried** [comment]
'explodes' is probably the intended verb, as it implies thrusting in suddenly and 'explores into' is ungrammatical. The gargoyle is a she, and so I can't see any errors in that section either.

You are correct about the missing 'be' in the Urta paragraph.

**Comment by Frahuenheld** [comment]
Not the gargoyle, the demon from her memories.
"An omnibus who fancied herself a master..." First it's a woman/herm.
" He challenged her (the previous master) to a duel..." Now is (just) a man.
Then the rest of this memories a lot of ambigous terms are used.
I know it's something with little matter (or lets be frank, it's stupid) but I can't let things just like that xDu

**Comment by Frahuenheld** [comment]
By the way, another mispell.
¤ Missing space - That must be from when I asked for a Naga variable on this scene.
She’s not much of a fighter, and in one move, the situation is reversed. She’s flat on her back, gasping for air, and you’re sitting on top of her, holding her tightly between your knees(right here)holding her tightly. If she gets her wits about her she might still be able to escape, so you put your hands over her mouth and tell her to untie you in your most commanding tone.
