### ISSUE TITLE
col: 3 Error: The private attribute may be used only on class property definitions.

### ISSUE THREAD

**Issue by Korvas** [herp-a-derp/Corruption-of-Champions#661]
Hi, I've been trying to add custom material into the game and recently, I've been hitting a series of snags that I have no idea on how to solve and I have been looking like mad into it.
For whatever reason, whenever I add new stuff to any place that isn't of my own creation, I get a strange error where all sections of the script that are labeled as a private or public function stop working entirely. This happened when I added to tel'adre and to the desert.

as an example, this is what I added to the desert.as in scenes/areas/ just under the section about encountering alice and getting the wizards staff.. I don't encounter any syntax errors here.
//start of Script
			if (player.cor >= 50 && player.inte > 50 && flags[kFLAGS.FLAGHERE] == 0) {
				outputText("", true);
				outputText("Text Here\n\n", false);
				outputText("Text Here\n\n", false);
				outputText("Text Here\n\n ", false);
				outputText(Text Here\n\n", false);
				outputText("Text Here\n\n", false);
				outputText("Text Here\n\n", false);
				simpleChoices("Break the Barrier", Breakit, "Leave", gohome, "", 0, "", 0);
			}
		}
			public function Breakit():void
				{
					clearOutput();
						outputText("Text Here.\n\n", false);
						outputText("Text Here\"\n\n", false);
						outputText("Text Here.\n\n", false);
						outputText("Text Here\n\n", false);
						outputText("Text Here\n\n", false);
						outputText("Text here\n\n",false);
						dynStats("cor", +10);
						flags[kFLAGS.FLAGHERE] = 1;
						doNext(13);
						return;
				}
				public function gohome():void
				{
					clearOutput();
						outputText("Text Here.\n\n", false);
						dynStats("cor", -10);
						flags[kFLAGS.FLAGHERE] = 1;
						doNext(13);
						return;
				}
                    }

now, after this addition, the private functions for the desert mirage and the walkingdesertstatboost are encountering the syntax error "col: 3 Error: The private attribute may be used only on class property definitions." I have no idea why its doing this and I have no idea how to fix it. As I said, I'm encountering this after all the new additions I make to any page, no matter how big. Can someone please help?

**Comment by Gedan** [comment]
Not really an issue to be discussed here; I'd take it to the forums if further follow up is required.
