### ISSUE TITLE
Ember impregnates through Sandwitch contraceptives, and is generally annoying.

### ISSUE THREAD

**Issue by Garzhad** [herp-a-derp/Corruption-of-Champions#663]
As per the title, Ember seems to completely ignore Sandwitch contraceptives for some reason. Also, while probably intentional, his constant badgering me for sex and getting pissy when I deny him during heat/rut(largely because of the aforementioned problem of him impregnating the pc through contraceptives) is about as annoying as Marble's old morning-rapes before That was addressed.

Let me sleep, ye scaley bastard.

**Comment by Garzhad** [comment]
Negative. Ember's Heat Sex impregnates straight through sandwitch contraceptives where no other does. It's an automatic impregnation.
else if (player.pregnancyIncubation == 0 && (flags[kFLAGS.EMBER_GENDER] == 1 || flags[kFLAGS.EMBER_GENDER] == 3) && player.inHeat) {getKnockedUpByEmbrahBroBaby();
player.knockUp(PregnancyStore.PREGNANCY_EMBER, PregnancyStore.INCUBATION_EMBER, 1, 1);

**Comment by Garzhad** [comment]
http://imgur.com/QZuHYkL
This shouldn't be happening... and yet it is. No other thing in the game can impregnate my pc after taking the brown pill. Ember can. BUG.

**Comment by rentazilla** [comment]
@Garzhad appears to be correct that Ember can impregnate a PC on contraceptives—Ember calls `knockUp()` with the fourth argument set to `1`, [which bypasses contraceptives](https://github.com/herp-a-derp/Corruption-of-Champions/blob/14aa1a6e3752ab3528640d5666415d3449dd7fef/classes/classes/Character.as#L451).

Whether that's a *bug* is a different story. The argument was *deliberately* set to 1; that may mean that Ember's authors wanted the character to bypass contraceptives, or it may mean that they passed 1 without knowing all of its side effects.

**Comment by Gedan** [comment]
Paging @Fenoxo

**Comment by Fenoxo** [comment]
Truth be told I don't really remember. Up to you Geddy.

**Comment by Garzhad** [comment]
There are more virile npcs/mobs that don't bypass, don't see why Ember should get special treatment in that regard.

**Comment by IndirectOne** [comment]
Yeah, I'm pretty sure the always impregnate option is only there to handle things like bee eggs, spider eggs and such - 'pregnancies' that don't depend on the player having any eggs of their own ready, or even a womb in some cases.

**Comment by Zeikfried** [comment]
Not a bug. From QB's original *Last Ember of Hope* doc, "Bred by Ember" section:

//Only occurs if the PC has a pussy and is in heat; Ember must have a dick; both must not be pregnant.
//In case Ember and the PC are herms, both being able to impregnate and be impregnated. One of the scenes will be randomly choosen.
//Ember never fails to impregnate the PC or be impregnated.


This portion of Ember code predates the introduction of witch/farm contraceptives, so whether it should ignore them is arguable. Precedent bypasses (with PC and Edryn) require massive cum volume and/or higher-than-normal virility on the part of the male, which Ember does not satisfy.

**Comment by IndirectOne** [comment]
Since it predates the contraceptives I would say change it. The difference with Edryn is that it's just a chance to bypass, not 100% of the time.
(also, it's the player getting knocked up here, so people are a bit more annoyed about it)

**Comment by Gedan** [comment]
Ye, change it.

**Comment by IndirectOne** [comment]
Should now be fixed. 100% chance if you aren't on contraceptives, 0% if you are.
