### ISSUE TITLE
Switching away from flash?

### ISSUE THREAD

**Issue by kittyguy** [herp-a-derp/Corruption-of-Champions#667]
This might be better to post in the discussion forum but it says that my details match those of a known spammer when I try to register. So anyway, here it goes.

Flash is a dying platform. There is no way around that. For CoC to have a future it should move away from flash.

Are there any plans for move?

How much difficulty it would be to generate, say, a HTML5 build in addition to flash and air build?

**Comment by gardeford** [comment]
Your comment certainly sounds like spam. i'm glad the sites robots could pick it up.

**Comment by Gedan** [comment]
After laughing myself half to death, time to actually respond.

No, currently there are no plans to try and rebuild CoC in any way shape or form. It's simply too massive of a task for little-to-no gain. I played around with a potential typescript port of TiTS, but abandoned that when I realised how immature Typescript actually is, how terrible JS/HTML/Web tooling is (fuck Node, fuck Grunt) and how I would literally be fixing all of the same shortcomings that AS3 has all over again, just in a language that required slightly different approaches to the problems.

Flash as a platform is not dead, and we're at the very least a year if not more away from that seriously being even *on the fucking table*, depending on acceptance and uptake of ES6 Javascript. Even then, there's the underlying problem that Javascript fixes nothing that AS3 fails at; you're subject to the exact same problems, just requiring subtly different workarounds. Also lets not talk about browser standardisation of various HTML/JS functionality, which is just going to add even greater complexity.

**Comment by kittyguy** [comment]
well, let's put it this way.

I own about half dozen devices on which I can run usable, modern web browser which can presumably run FoE or can be updated to the most recent and greatest version that can. On the other hand, half of them does not have any flash (nor air) whatsoever in any shape or form. It is obviously in part due to collecting obscure devices. With effort you can put flash on iOS and on many Chinese Android tablets flash somehow 'just works' although it is officially not supported on Android.

Yes, JS is not in any way better than AS. It is in fact very similar which is the reason HTML5 seems like viable target for conversion. Depending on the coding style it might take just a giant sed expression to convert the AS to valid JS. Or it may be more difficult if some AS features actually different from JS are used extensively.

Yes, browser discrepancies do exist although they are not as bad as they used to be. Toolkits that cover up the discrepancies do exist although they are not perfect. Either way, only part that really deals with this is the mainview. Rest just generates simple text using core language features for math.

**Comment by Gedan** [comment]
No.

Just no.

If you seriously think that you could convert a project in the size and scale of CoC from AS3 to JS using "a giant sed expression", then I'm obviously wasting my time.

> n666: tell him to get started under the condition to not get help from you gedan
