### ISSUE TITLE
Minor D3 Doppleganger Bug (And question.)

### ISSUE THREAD

**Issue by wyvvern** [herp-a-derp/Corruption-of-Champions#670]
In the D3 Doppelganger male victory scene there's this: 
```
else if (player.skinType != SKIN_TYPE_FUR) outputText("  You clamber on top of him, the rough mingling of your fur sparking deep urges within you, your animal half dreaming of frenzied, bestial mating in the wild. Your hardening dick presses against his [tail] and he groans raggedly in response.");
```
My test character is a vanilla male human - no mutations at all (ie  no fur.)

2 bugs. !SKIN_TYPE_FUR shouldn't have "the rough mingling of your fur" in the text.  Nor does my character have a beastial half. Also, it's perfectly possibly to have fur without a tail, so even if you changed !SKIN_TYPE_FUR to SKIN_TYPE_FUR it doesn't work.

The second is parser/monster related: this paragraph appears as:  "Your hardening dick presses against his !Creature has no tails to describe! and he groans raggedly in response."

There's no 
```
    this.tailType = player.tailType;
```

in the monster constructor. 

My question is this: has anyone actually beaten this fight without cheating? Is it meant to be winnable? I've tried several builds with various stats and at various levels and the lust always outpaces any damage I can inflict. The only way I saw this scene was to cheat - I coded in an uber-weapon.

**Comment by Gedan** [comment]
Yeah, it's easily beatable without cheating if you know what you're doing.

That said, it needs a fucking lot more work to make it better. It's... in an acceptable place, but the amount of effort required to bring the "vision" to completion is going to have to wait for another day.

I'll look at getting a fix-build out this weekend though for the little things.

**Comment by wyvvern** [comment]
Thanks for tending to the bugs. 

As for the balancing of this fight - it's still an issue. The problem is the HP of the monster vs the damage the player can output per round. If the player's toughness is too high it makes it difficult to win.

Take a character at level 12 with the following perks: Brutal Blows, History: Fighter, Strong (starting feat), Thunderous Strikes, Precision & Weapon Mastery. (Also had Strong Back 1& 2 and Resistance but those are irrelevant.) I pretty much designed this character for this one fight. 

My stats were so skewed I had 4 perk points left over I couldn't invest. (Str 100, Tough 24, Speed 25, Int 26)

With the huge warhammer in my testing I was outputting an average of 140 damage a round. The actual damage was all over the place, from lows of 29 to crits of 253.

You have 5 rounds to win. If you're lucky enough to hit on all rounds you can do a total of around 700 damage. Actual numbers will vary but I ran 10 or so tests and that's what I averaged it out to.

The monster gets the player's HP plus a bonus HP of  250. 

With a toughness of 50 and the tank perk you'll have 350 HP and win all the time.

With a toughness of 75 and both tank perks you'll have 505 HP and win half the time. 

With a toughness of 100 and both tank perks you'll have 580 HP and almost always lose. It's very difficult to output 830 damage in 5 rounds - especially when it's completely RNG dependent if you'll hit on them all, and the damage can vary so wildly even if you do.

This means higher level characters or players who grind out their stats via Vitality Potions or exploring the forest repeatedly are actually less likely to win then lower-level players.

Now I could understand punishing players who are too corrupt - but it makes no sense to me to punish players who are too healthy.

Which is why I had problems with this fight. I'm kind of a perfectionist. It's perfectly possible (though admittedly tedious as heck) to get all your characters stats to 100 at level 1. You can do it without ever drinking a single vitality potion and without using the save editor.

**Comment by wyvvern** [comment]
Quick addendum: only reason I'm making an issue out of this is because it leads to a Game Over. If it was just a rape loss or if you could know in advance somehow that you don't actually need to do this fight at all to do the rest of the stronghold, I wouldn't be following up on it.

All the other Game Overs are because the player made "bad" choices.

**Comment by Fenoxo** [comment]
Fixt the typo shits. As for balance... eh
