### ISSUE TITLE
one loss scene to demon Sheila does not reset lust or HoursSinceCum - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#677]
The scene in question is the loss rape that may trigger for PCs with cockArea < 56, specifically the fork with balls (inflicts ball growth and 100% Sheila preg chance).

Happens irrespective of triggering by combat loss or "LetHerFuck" dialogue option.

**Comment by Zeikfried** [comment]
correction: cockArea < 56

**Comment by IndirectOne** [comment]
Should now be fixed.
