### ISSUE TITLE
missing italics in Frosty's intro dialogue - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#679]
Affected text below is free of italics:

You have to take a step back to process everything she just blurted out; you also take the flyer from her just so she stops pushing it against your face. “So do you wanna come to my stand, do ya, do ya, do ya!?” You answer her with an uncertain “yes”, still wondering what she just said.

**Comment by IndirectOne** [comment]
Should now be fixed.
