### ISSUE TITLE
Giacomo still offering Dual Belts to herms that already own them - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#682]
Giacomo will go through his entire Dual Belt spiel and present a yes/no choice even if PC owns a Dual Belt key item already. Only if player selects 'yes' will they be given bold-text notification that they already own a Dual Belt. Other Giacomo-sold toys check for the key item and present the bold-text notification prior to triggering the spiel and yes/no choice. Please move the check to the same place for Dual Belt, for uniformity.

see also #603

**Comment by IndirectOne** [comment]
Should now be fixed.
