### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by Bauhaus250** [herp-a-derp/Corruption-of-Champions#683]
If I go to Data>Save and click on any of the slot options, nothing happens. If I choose the "save to file" option,  the window pops up for me to choose where i want it saved on my pc, but if i click the "save" button here, again nothing happens.
I have restarted the game multiple times and tried each method of saving with the same results. I have also deleted and re-downloaded the game multiple times and tried to save with the same results. (Yes I have checked the "load" option after each attempt)

I use windows 8.1, with Chrome.
Not sure if this was the right place to put this, my apologies if it isn't.

**Comment by Fenoxo** [comment]
Strange. Seems to be a fairly unique issue to you, likely a problem with your local machine. Gonna close this unless we can find a way to reproduce it on other hardware.
