### ISSUE TITLE
Isabella does not gain affection from "Offer Oral" if PC refuses return fellatio - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#685]
If a PC with eligibly small penis offers cunnilingus to Isabella on the plains and then turns her down for reciprocal fellatio, she does not gain the usual 2% affection from the cunnilingus. There is no message to indicate any kind of disappointment on her part; the PC is simply returned to camp.

to replicate:
-make a PC with suitably small cock
-unlock plains, meet Isabella
-meet Isabella 2nd time
-select "Offer Oral"
-select "No"

**Comment by IndirectOne** [comment]
Fixed. Isabella's affection was only increasing in 1 out of 3 of the possible routes out of that function. Now adds 5 for all.
