### ISSUE TITLE
several pregnancy stage notifications missing bold text - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#686]
Several pregnancy stage markers, below, are missing bold text.

-satyr (both vaginal and anal):
You find that you’re feeling quite sluggish these days; you just don’t have as much energy as you used to. You’re also putting on weight.
Your belly is getting bigger and bigger. Maybe your recent urges are to blame for this development?
Sometimes you feel a bump in your pregnant belly. You wonder if it’s your baby complaining about your moving about.
With your bloating gut, you are loathe to exert yourself in any meaningful manner; you feel horny and hungry all the time...
The baby you’re carrying constantly kicks your belly in demand for food and wine, and you feel sluggish and horny. You can’t wait to birth this little one so you can finally rest for a while.

-basilisk (observed with Benoit):
Drops of breastmilk escape your nipples as your body prepares for the coming birth.

One satyr pregnancy notification is only partially-bolded, in comparison with the usual entirety of the notification:
You can feel the strangest fluttering sensations in your distended belly; <b>it must be a pregnancy</b>. You should eat more and drink plenty of wine so your baby can grow properly. Wait, wine...?

It's also a bit odd that egg-pregnancy from Benoit causes (and draws attention to) lactation.

**Comment by IndirectOne** [comment]
Fixed the Satyr pregnancies so they're fully bolded. Didn't fix the breastmilk text as this appears in several pregnancies and is never bolded.

**Comment by Zeikfried** [comment]
It might be appropriate to do so; all other lactation notifications not tied to specific scenes (increase, decrease, cessation) are already in bold text.
