### ISSUE TITLE
phantom commas in cock descripts - 0.9.2 and earlier

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#687]
Occasionally cock descripts will include an unnecessary comma, as below:

A beanbag with a pair of testes swings heavily beneath your big, cock.
A nutsack with a pair of balls swings heavily beneath your ample, cock.

As an aside, the cock in question was 5.3 inches long and 1.3 inches thick, so 'big' and 'ample' are also inappropriate descriptors.

**Comment by IndirectOne** [comment]
Fixing this would take extensive changes to the cockDescript system. There are several interrelated functions and various bypasses to force them to use a particular form of cock. With the number of ways this can be called with current code it would be difficult to prove that removing commas isn't going to screw up some other version of the description.

**Comment by Fenoxo** [comment]
What the fuck. This didn't used to be a problem. It's a pretty unforgivable error to have, in my opinion.

Sounds like you guys have fragged cockdescript.

**Comment by Gedan** [comment]
Cursory eyeballing of the descriptors leads me to believe that this may have been an issue for A LONG time that nobody has noticed/reported. The only recent changes that I can see anywhere near CockDescripts were made by @IndirectOne but I can't see how they would have introduced that. Prior to that, the last change to the file in general was in June, so...

**Comment by IndirectOne** [comment]
I've actually been working on cockDescript and related functions since seeing this issue a while ago. The phantom commas only appear in some versions of cockDescript and I think they're leftovers from some attempt to have multiple adjectives one after the next.

Anyway, once I finish testing I'll send in a pull request that should simplify and centralize a lot of this.

**Comment by IndirectOne** [comment]
Just uploaded a further patch. This should fix up the cock descriptions and make the code that leads to them much easier to follow.
