### ISSUE TITLE
abrupt cut-off in Benoit talk option - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#688]
The scene in question involves the PC making animal noises and Benoit guessing them, and becomes available at higher affection. I believe the error is tied to silly mode. The affected text is below, reproduced as it appeared in normal mode. "centaur" shouldn't be capitalized in this instance, either.

“What ze 'ell is zat supposed to be?” says Benoit, looking alarmed. You tell him it’s a Centaur

**Comment by IndirectOne** [comment]
That scene is truncated in code too, it seems to start out of nowhere and end abruptly. I can't locate whatever document originally had this text in it (it's not in the Benoit gdoc), so there's no easy way to fix this apart from chopping it out.

Not fixed. Hopefully someone has the original text.

**Comment by tmedwards** [comment]
I don't know.  Not every scene needs a intro and outro.  It reads like something from a sitcom, really.
> *camera pans in*
> […guess what makes the noise skit between Benoit and PC…]
> *camera pans out*

Admittedly, it probably would have been better with an extra non-silly-mode line, either a rejoinder from Benoit about centaurs or the PC gloating over having stumped him, but it works without it.

Anyway, it may be a little odd, but it doesn't feel like it's necessarily an error.  Well, apart from the obvious (miscapitalization of Centaur and missing period):
```ActionScript
			if(!silly()) outputText("Centaur");
```
Which should be:
```ActionScript
			if(!silly()) outputText("centaur.");
```

**Comment by Zeikfried** [comment]
It was originally supposed to reference a Unitaur, a stupid inside joke from the old /vg/ CoC topics, before it was changed by Fenoxo. Unfortunately I only have Nonesuch's original scene, transcribed below, and not whatever replaced it in Fen's final writeup.

__

”Gnoll.”

 You make a gentle humming noise.

“Bee maiden,” says Benoit after a moment.

You stamp your feet and snuffle and snort.

“Minotaur,” says Benoit immediately.  You sigh - he’s too good at this game, and you’re running out of creatures.  Thinking briefly, you make a clop-clopping whilst slapping the counter, throwing in a bit of heavy breathing for good measure.

“What ze ‘ell is zat supposed to be?” says Benoit, looking alarmed.  You tell him it’s a Unitaur.

“A what?”

You explain that a Unitaur is like a white centaur, only it has a horse’s face.  It has massively strong human arms though, and it can cast magic better than anyone, and it can go faster than a cheetah, and… you can’t help yourself and begin to giggle at the expression of terror that has emerged on Benoit’s face.

“Oh, I see.  You are pulling my tail.  Very amusing.”  You laugh even harder at the expression of wounded dignity which replaces the terror.

**Comment by IndirectOne** [comment]
That's exactly how the scene would appear with silly mode on.
Fen just cut it off and replaced Unitaur with Centaur in the fourth to last paragraph.

**Comment by Zeikfried** [comment]
It might be appropriate to move the end to immediately after "he’s too good at this game" or limit the scene to silly only. Benoit would know what a centaur is.

**Comment by tmedwards** [comment]
It's not a matter if Benoit knows what a centaur is, it's a matter of if he can deduce what the PC is describing.  It's aural charades.

**Comment by Zeikfried** [comment]
And as noted, Benoit is very good at the game. He'd have to be.

Keeping it as is only jerks the reader out of the conversation at the moment it becomes interesting.

**Comment by Fenoxo** [comment]
Fixt via 2f3a4cf276b6c39ad4367657eba2818f23919d4b
