### ISSUE TITLE
no italics/bad grammar in camp Jojo meditation refusal - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#690]
When corruption is higher than 10, follower Jojo tries to railroad the PC into meditation instead of offering usual 'Talk', 'Appearance', etc. upfront. If refused, some dialogue in the resulting scene is missing italics.

You assure Jojo you’re fine, and that you’ll consider his offer. “<i>But... I-We... Alright, but please do not let the corruption get the better of you. You’re my friend and I couldn’t bear to lose you to its vile influence.</i>” Then he recomposes himself and asks, “so... is there anything I can assist you with?”

Properly written (with italics added), it should go something like:

You assure Jojo you're fine, and that you'll consider his offer. "<i>But... I... we...</i>" he stammers. "<i>Alright, but please do not let the corruption get the better of you. You're my friend and I couldn't bear to lose you to its vile influence.</i>" He recomposes himself and asks, "<i>So... is there anything I can assist you with?</i>"

**Comment by IndirectOne** [comment]
Fixed.
