### ISSUE TITLE
non-printing character and ellipsis abuse in camp Jojo's 'Forest' talk - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#691]
Relevant text is below. The non-printing character is in the first sentence; the ellipsis abuse is throughout. There is also a five-dotted ellipsis in the third sentence.

That’s terrible... you can only imagine what you[non-printing character]’d feel like if you returned to Ignam and saw it destroyed... your family, your friends... You put a hand on the monk’s shoulder, intent on comforting him for the moment.

“<i>Thank you [name]. I was born there and seeing that....</i>” The monk falls silent again.

**Comment by IndirectOne** [comment]
Should be fixed. There were also some missing spaces. That is some very old dialogue and code.
