### ISSUE TITLE
Quinn intro still plays on first visit to tower if you go at night -0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#692]
Upon the first visit to T'A's 'Tower', Quinn's intro plays no matter the hour. The player may still select 'Study' and, if the time is late enough, the game will then note that Quinn (who just finished introducing himself) is absent.

Unsure of best fix. Might be simplest to make Quinn's intro sensitive to the hour, but that would involve rewriting the successful 'Study' outputs.

to reproduce:
-discover Tel'Adre for the first time
-wait until 18:00 or later
-enter Tel'Adre, go to Tower
-after Quinn's introduction, select 'Study'

**Comment by IndirectOne** [comment]
I added some new variations that cover finding the library and studying without having met Quinn. The encounters go back to normal once you've met him at least once.
