### ISSUE TITLE
Urta finds someone else's camp?

### ISSUE THREAD

**Issue by Otaku-chan** [herp-a-derp/Corruption-of-Champions#695]
Urta claimed her scouts had found my camp, //with marble// occupying it.

However, this is quite impossible, //as marble is currently gone from my camp// to get one of her sisters.

She had left a few days before Urta brought her up, //and was still gone when I returned to camp after the 'Urta discovers Marble' event.//

Who's camp did she find?

**Comment by IndirectOne** [comment]
Fixed. Urta's code only checked if Marble was a follower - which was fine until the purification quest got added in.
