### ISSUE TITLE
When suddenly… PANTS!!

### ISSUE THREAD

**Issue by Otaku-chan** [herp-a-derp/Corruption-of-Champions#696]
During Amily's pregancy, when you approach her in the ruins, it describes her as specifically not wearing pants, also mentioning that she can't fit in to them.

Ask her to drink a Purified Incubus Draft, and suddenly she has pants on, and the following two 'pages' play out as though she's not pregnant.

After returning to camp and visiting the ruins again, she has returned to being pregnant.

Two options of the top of my head are to have pregnancy\non-pregancy conditionals for various sections of the scene, akin to the various parts of the champion's descrioption\body or to simply disallow the incubus draft while she is pantless.

**Comment by IndirectOne** [comment]
Added some alternate text to the bit dealing with drinking the incubus draft. If she's very pregnant she now lifts her shirt to give you a better look and after growing her new penis she can't see it over her belly.
