### ISSUE TITLE
Kid A bug?

### ISSUE THREAD

**Issue by thethreethatareone** [herp-a-derp/Corruption-of-Champions#697]
I don't know about you all but Kid A has completely bugged out for me, whenever I try to give her a weapon the proper text comes up but I have no options (not even a back button) and the game completely freezes so I have no choice but to exit and restart it. Which btw I am on an Android with the 0.9.2 update

**Comment by IndirectOne** [comment]
Yup. It's been brought up before, in #666 and #644. Those are closed so they're easy to miss.

The fix is coded and merged in, it's just that a new release hasn't come out yet. You can try the CoC Alpha build, which already includes the patch. https://github.com/herp-a-derp/CoC-Alpha

**Comment by thethreethatareone** [comment]
Well yes I suppose so but I was informed that the mobile downloads don't work here?

**Comment by thethreethatareone** [comment]
Oh well this is fantastic, downloading the mobile from here deleted the one I got from fenoxo's site and proceeded to not work, so I just lost everything I have worked for, all 10 characters (which by the way all had max stats and we're level 20, and had almost all possible camp followers, plus each one was a different species.) deleting all the man hours I spent to get all those...so I suppose the problem is fixed, just not at all in any way is it good.

**Comment by Fenoxo** [comment]
Try reinstalling the one off the main site - the saves might still be there.

**Comment by thethreethatareone** [comment]
It's all gone...
