### ISSUE TITLE
Character creation details

### ISSUE THREAD

**Issue by IndirectOne** [herp-a-derp/Corruption-of-Champions#698]
I'm going through the CharCreation file, replacing numbered function references and I've noticed a few little details that might be mis-set.

Lean men get size 2 hips instead of the size 4 hips average men receive. Slender women get size 6 hips, the same as average women. I think slender women should get size 4 hips instead.

Similarly curvy women get D cup breasts but slender women get C cups, the same as average women. Tomboyish women get B cups. Should slenders get B's as well?

Curvy girls get a hip size of 8, which is still classed as ample. Curvy hips start at 10, so should they get upgraded to that value?

Average men have a tone of 60, average women a tone of 30. Lean men and slender women both add 5, thick men subtract 5 but curvy women do not. Should they?

Also, girly men set their tone to 26 and tomboyish women set theirs to 50. So tomboyish women gain 20 tone and girly men lose 34, making them lower tone than anyone except curvy women. Is that correct, or were girly men supposed to subtract 20 for a tone of 40?

Girly men get -2 strength and +2 speed. Should tomboyish women get +1 or +2 strength and -1 or -2 speed?

Tomboyish girls have a butt rating of 0. That's even lower than the butt rating of lean men and slender women (both at 2). Should it be raised to 2?

**Comment by Fenoxo** [comment]
On the hips, I can't say for sure without looking at the values for the hip description, and I don't know where that is anymore since CoC is now a portal to the nightmare zone.

Slender chicks could have B cups and tomboyish A cups, I guess. I don't think it greatly matters one way or the other.

Curvy hip upgrade sounds fine.

On curvy subtracting 5, sure.

Tone settings are fine.

I'd be fine with a +1/-1 for tomboys

2 is fine.

**Comment by IndirectOne** [comment]
Checked up on the hip measurements:
Size 2 hips are usually described as slender, narrow or thin. Size 4 as well-formed or pleasant. Size 6 as ample, noticeable or girly. Size 10 as flared, curvy or wide.

Lean men get size 2, slender women get size 6.
Average men get size 4, average women get size 6.
Thick men get size 4, Curvy women get size 10.
Girly men get size 2, Tomboyish women get size 2.

So maybe slender girls should get size 4 and perhaps girly men should get size 4 as well.

**Comment by Fenoxo** [comment]
Eh
