### ISSUE TITLE
Owca combat bug

### ISSUE THREAD

**Issue by IndirectOne** [herp-a-derp/Corruption-of-Champions#699]
I think I've just found a very old bug in Owca.
When you help the villagers as a sacrifice they take away your weapon and chain you up. In code they do this:
		player.createStatusAffect(StatusAffects.Disarmed,0,0,0,0);
		flags[kFLAGS.PLAYER_DISARMED_WEAPON_ID] = player.weapon.id;
		player.setWeapon(WeaponLib.FISTS);
		monster.createStatusAffect(StatusAffects.BowDisabled,0,0,0,0);
		if(player.str < 80 && player.spe < 80) {
			monster.createStatusAffect(StatusAffects.AttackDisabled,0,0,0,0);
			monster.createStatusAffect(StatusAffects.RunDisabled,0,0,0,0);
			monster.createStatusAffect(StatusAffects.PhysicalDisabled,0,0,0,0);
		}
		else {
			if(!player.canFly()) monster.createStatusAffect(StatusAffects.RunDisabled,0,0,0,0);
		}

But in the combat.as file it's the player who's checked for these various status values. So BowDisabled, AttackDisabled, RunDisabled and PhysicalDisabled should all apply to the player. Also I think the code for testing those status effects is a bit bugged itself, probably needs a rework.

Only reason I bring this up rather than fixing it right now is that it has been broken so long. Should it be fixed?

**Comment by Fenoxo** [comment]
It's a bug. Fix.

**Comment by IndirectOne** [comment]
Ok, turns out they should be on the monster but the checks pointed at the player. Anyway, fixed.
