### ISSUE TITLE
Italics

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#700]
¤Jojo (Talk > Sand Coven) - From here the whole text is on italics.
You tell Jojo about the poor mind addled thing you found sitting in a tub of milk acting as a slave to the sand witch coven.
He shudders like a child being told a scary story and asks, “What did you do?”
You tell Jojo about how the Sand Mother told you the bath girl was unfit to be free and how they care for her because she can’t care for herself.
Jojo reacts by putting his chin in his hands and thinking, “Well... I guess that’s the human thing to do, especially since she doesn’t seem to be corrupted. Maybe these sand witch covens aren’t all bad, still hard to believe that they’re on our side though....” He looks up and shrugs, “Any act of charity though is a good thing. I do hope the poor girl will be alright.”
You tell Jojo about the cum witch, the herm witch responsible for inseminating the witches there, acting as a father to the others. When you do he scratches his ear, “Like I said, I don’t get why sex is so overly important to these creatures but whatever, continue.”
You tell him how you tried to remedy the current cum witch’s situation by asking the Sand Mother to make more cum witches.
He whistles low, “That’s a bold move Seizobaru. It seems like they would want that though, it’d allow them to, er, you know... more often, and make more sand witches in the long run wouldn’t it?” As the question sound rhetorical you plow on ahead.
Having concluded the conversation the two of you stand and Jojo gives you an appreciative pat on the shoulder, seeming more fond of you.

¤Ceraph (Partswap) - When she offers you this the last two paragraph are on italics.

**Comment by IndirectOne** [comment]
Right - both fixed.
