### ISSUE TITLE
Possible bugs

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#701]
¤ Helbound (Fuck It as female) - Possibly a missing scene because there are three spaces between the last text and the rewards.
...In your fury, you barely notice that he looks disappointed and maybe even somewhat sorry.

You grab 16 gems and 29 XP from your victory.

¤Imp Horde (Zetaz's lair) - Female sex doesn't raise corruption (already at 36)

¤Trap Oil - Shouldn't it show how much thin you became?
You flex your arm in interest. Although you have become thinner, your muscles seem to have become more defined.

You feel an odd tightening sensation in your midriff, as if you were becoming narrower and lither. You frown downwards, and then turn your arms around, examining them closely. Is it just you or have you lost weight?

**Comment by IndirectOne** [comment]
Fixed the hellhound and imp horde. I wasn't sure about the trap oil, so I left it alone.
