### ISSUE TITLE
Mispell and bug on Phylla scene

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#702]
¤Phylla (Use Vagina on first time having sex) - A little mispell (maybe I'm wrong) on the final scene and it didn't depleted my lust. It was on 50 and I don't have any minimum lust perk.
You almost collapse on to (should be 'onto'?) her as your body attempts to recover from pleasure. You catch yourself planting both your arms on either side of Phylla’s face, hanging over her. She reaches up and wraps all her arms around you, bringing you down to lay next to her. The shy ant morph turns her head and kisses you one final time before you both pass out in each other’s embrace.

**Comment by IndirectOne** [comment]
OK, fixed. You now collapse onto her and you have a player.orgasm() afterward.
