### ISSUE TITLE
Oh god, the mispells

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#703]
Sorry for that title xD

¤ Izma (coming to camp) - Mispell
What makes you curious is how she decides to keep her bed at a distance from your own. You give her a wave and tell her it’s okay to sleep near you. She looks at you quizzically in response. “Well...” she stammers, “I thought my Alpha would want me to sleep some distance away,” she says. With a hasty reassurance, you inisist (should be insist) that she place her bed closer. Eager to serve, she drags the bedroll adjacent to your own and smiles at you bashfully.

¤Kath (training with Urta - first scene) - Double 'until'
“I will! I swear it! Please, just, please, don’t make me stay in this thing all the time!” the cat whimpers. Urta pays no heed to Kath’s pleas though. “If you perform well during the training, I’ll let you off the belt to blow some steam, but until until (right here) then - get used to it.”

¤ Kath (training with Urta - handjob contest) - Mispell
Urta, meanwhile, manages to hold it a little longer, but even as the first few splatters of Kath’s kitten-cum land on her black-nippled breasts, the vulpine her (should be 'herm') is launching her own assault, great gobbets (I think it should be 'gobblets') of jizz belching from her cock-head, spraying right across Kath’s face and breasts and oozing down to paint her stomach. Meanwhile, Kath soaks Urta from the waist up with her prodigious orgasm, yowling in pleasure and uncaring of the fact she’s getting Urta’s salty spunk in her mouth. By sheer coincidence, the bulk of their orgasms land on each other, rather than on you.

¤Kath (training with Urta - sparring defeat) - A possible mistake
Urta sighs softly and begins to tighten her hold. “You can give up, or you can get hurt, that’s the way this move works.” Kath furiously struggles and wriggles in the fox’s grip, but eventually decides Urta’s right. “Alright, aunty, aunty, I give!” she pleads. Urta promptly lets her go and stands up. “...Aunty?” she asks, curious. Kath gets up and shrugs; “I don’t have an uncle (I think it should be 'aunt'),” she replies.

¤Kath (training with Urta - Spitroast) - Possible mispell
Urta grabs Kath from behind, locking her arms so she can’t advance on you. Never one to look a gift (I think it should be 'gifted') horse in the mouth you start to play with kath’s nipples through her uniform. Kath’s knees soon buckle and Urta has to go from holding her back to holding her up.

**Comment by tmedwards** [comment]
The latter two are correct as-is.

**Comment by IndirectOne** [comment]
Ok, first three are corrected. Funny thing is the double until doesn't appear in code. I chopped it and the words to either side out and rewrote them. If there were any non-printing characters screwing with things hopefully that fixes it.

**Comment by Frahuenheld** [comment]
Yeah, that proverb is pretty known in my country but I wanted to be sure x3

**Comment by Zeikfried** [comment]
In re: Sheila, 'swaps' is the intended word, as in 'swap meets'.

**Comment by Frahuenheld** [comment]
I'm not sure in this one if the mispell is where I pointed here or if the first 'she' should be replaced by a 'he'.

¤Arian (giving Sucubi Milk to male Arian) - Mispell
Arian gasps and moans, a throaty, girly moan. She opens her robes to watch as the changes sweep through him (should be 'her'). First the smooth scales of her chest begin flaking off, making way for a pair of erect nipples; following the growth of said nipples, her previously flat chest begins inflating, growing into perky scaly breasts. Down below, Arian feels a wave of heat gather between her legs; once she spreads them, she gasps. A slit appears, the surrounding scales become smaller and softer, forming what looks like a tight little pussy. Arian’s newly formed labia puff up and juices begin flowing freely from the moist passage, even as Arian’s little pleasure buzzer appears to slightly part her labia in a clear invitation for you to explore its depths.

**Comment by IndirectOne** [comment]
The towel and Arian's her have been fixed.

**Comment by Frahuenheld** [comment]
I'm going to take advantage that IndirectOne is working so hard.

¤Arian herm (Dildo) - mispell
Arian pants, still winded, though her breathing seems to have returned to a more normal level. She can’t help but grin at your compliment. “Don’t be silly, Seizobaru. I’m the lucky one. But I’m really glad you think so highly of me.” Why shouldn’t you? She gave up her birth-gender, just to better please you - why, any girl who passed up a chance to snap up someone was (should be 'as') sweet as Arian was a fool, but they’ll never amend their mistake, because she’s all yours now. With that you slither around in the bed so that you can glomp onto your girlfriend, rubbing your light skin cheek against her own smooth scales, hugging her tightly to you.

¤Arian herm (Blow her) - Possible a code error.
“Yes, I liked it very much! Though I hope you’ll let me return the favor... somehow,” She says, releasing you from between her legs, while her tail lazily curls to gently massage your neck in a sign of affection.

You tell him (should be adapting to Arian's sex) you’ll think of some way she can return the favor, rolling your neck in pleasure as she rubs it with her reptilian tail.

**Comment by IndirectOne** [comment]
Those are fixed now as well. I have to say, Arian's parser tags seem annoying. I'm never sure what they'll translate into without double checking.

**Comment by Frahuenheld** [comment]
http://youtu.be/pt8VYOfr8To

¤Kiha (Talk) - Missing apostrophe
She snarls animalistically. “Oh, I fucking knew it! I say, hey, 'let’s take on the demons(there should be a ' closing Kiha's quote), and all you want to do is fucking analyze my feelings. Of course you do! What good are you, anyway? What use is a champion who just sits around talking, huh? How is that going to fuck up Lethice, topple the demons? Huh?”

¤Kiha (Dominate - Female PC) - Mispells
“Like a moth to an open flame! If all some demon has to do is fake their defeat and spread her (should be 'their') legs to get you into this position, then you will be easy prey indeed. The real world doesn’t arbitrarily roll over and concede defeat after a friendly spar! The fight’s not over til (I think it should be 'till') it’s over, and right now it looks like you’ve lost. Submit, and let me do what I do best.” Kiha coos confidently. You’re in for it now.
...
“Ha! The Champion still has some fight in them (should be him/her)! Keep me here if you can, wimp! I WILL pin you down and cum all over your face! You’ll lap it all up like a good little girl to bo- UGH!”

¤Herm Ember (Blowjob) - Mispell
You take the first three or four inches inside with ease, pausing to run your tongue across the glans and the urethra, savoring the taste of draconic pre-cum; rich and thick and tangy, cool and surprisingly refreshing. You enjoy the taste for a few long seconds, the (should be 'then') press on, swallowing inch after inch.

**Comment by Frahuenheld** [comment]
And more.
¤Cotton (Tantric Sex) - Missing word and a mispell.
She leads you to a private area in the gym, a large room where one side of the wall is covered in mirrors with a long bar across it. You’d guess this room is used for dance lessons, or other activities that require large amounts of space. She sets up a large mat on the floor, big enough for the both of you to sit on and then some (right here), and proceeds to strip. “It’s best to do this naked... we don’t want our clothing to block our spiritual energies. Or, y’know, other things,” she says with a light laugh. You nod and strip down as well.
...
Cotton returns the favor, her short-snouted mouth latching on to one teat and sucking it relentlessly. The sensations you get from this are, if anything, greater than normal. Your nipples feel like they’re on fire, with every molecule aching to be touch (should be 'touched'), licked, sucked and teased. You feel a familiar sensation welling up in your breasts as milk begins pouring into Cotton’s mouth. She grins as best she can without letting go of your tit, eagerly drinking down your milk. In yet another moment of trepidation, you realize you can taste your own milk slipping over Cotton’s tongue. You smack your lips. It tastes sweet and creamy, and oh-so warm. Cotton moves to your next nipple, letting the first dribble milk onto the both of you. Again Cotton sucks on your milk-leaking nipple for a moment before it begins dispensing its precious cargo into her mouth. You taste every gulp, each one sweeter than the next, before Cotton pulls back and smacks her lips together. “You taste so sweet, pet. I simply must have you around for breakfast...”

¤Minerva (Talk) - Mispell
“With her enjoying the orgasm, I struggled and managed to get away. In the fight, it dropped one of those 'teeth' the other sharks had forced on me, but this one had a strange sheen. I grabbed the thing and... just swam and swam until I reached the shore, then ran into the forest and just... I just... I felt like giving up. The world had tried to kill or rape me since I got here... it was probably the lowest point in my life. I knew I needed to get stronger. Stronger like the tigershark and sharkgirls. I knew that those sharks were stronger then (should be 'than') me and eating their fishy tasting things, so I took that glowing tooth and swallowed it. That’s how i got these stripes of mine,” the siren explains as she curls up in her spot, holding her knees to her chest. For a moment you think she’s isn’t going to continue her story, but she starts back up, voice slightly muffled by her knees.

¤Shouldra (Sharkgirl with Female PC) - Missing punctuation
Now as alarmed as she is, you start to pull back and get up, but are stopped dead in your tracks by a surprised 'oooh' coming from the now very-flushed girl before you. Your hesitation costs you your chance of escape as she brings her newly enlarged arm to bear, grabbing you roughly by the back of the head and shoving you back between her legs. As if in concert, the shark-girl’s labia surge forward, engulfing the strained garment attempting to restrain it, then slapping against your face with a juicy smack. Her clit follows soon after, growing to its full size before the rest of her body can catch up(right here) If she felt like it, ...

¤Shouldra (Googirl) - Mispell
-Second paragraph-
...The gelatinous mass shudders as the girl giggles, the sound strangely distorted. “This thing is so... empty,” she says in a curiously watery and gurgly voice. “It’s like taking over a sponge!” You raise an eye at the curious simile (should be 'smile'), but don’t think much of it. You have work to do.
...
-Fourth paragraph-
You continue shaping your creation until finally releasing it and rising to scrutinize your creation. You seem to have successfully molded a (should be 'an') eight inch long slime protrusion. Giving it a little flick that sends a shiver through the ghost girl’s gooey host, you confirm its solidity with a grin. The ghost girl offers...

**Comment by tmedwards** [comment]
> **¤Kiha (Dominate - Female PC) - Mispells**
> […] The fight’s not over til (I think it should be 'till') it’s over, and right now it looks like you’ve lost. […]

`’til` is a contraction of `until`, so the current text is simply a missing apostrophe away from being correct.  But, yes, `till` (no apostrophe) would also be correct.

<br>

> **¤Cotton (Tantric Sex) - Missing word and a mispell.**
> […] She sets up a large mat on the floor, big enough for the both of you to sit on and then some (right here), and proceeds to strip. […]

There's no missing word there, "*(some dimensional description)* and then some" is idiomatic.  It means that the preceding declaration is an understatement.  In this case, it means that the mat is larger than required to seat both Cotton and the PC (i.e. there's room to spare).

**Comment by IndirectOne** [comment]
The Shouldra + Googirl scene is supposed to use simile.
The rest should be fixed now.

**Comment by Frahuenheld** [comment]
¤Kiha (Gro+) - Missing 'her' and mispell.
Her entire body tenses as an orgiasmic (should be 'orgasmic') tremor rocks your system, both of you bellowing your pleasure. Gushes of her translucent fluids surge past her fingers are you continue to stroke the inflamed labia. Flopping to her side, Kiha trembles as the orgasm runs its course and eventually fades. She lies there for a few minutes more, enjoying the near-electric aftershocks running through (right here) body. Before she can even rise, however, she’s snoozing, curled up and pressing her knees into her too-big chest. Taking that as your cue to depart, you wriggle your ghostly essence back out of her back, reforming and recorporealizing behind her.

¤Benoit (Talk) - Missing apostrophes
You ask Benoite if she isn’t worried that demon customers won’t notice what she is.

“Zat is why I am wearing zis cunning disguise,” she says, patting her large beret. She lowers her voice to a growl. “And I talk like zis when I am serving zem. Grr. To be honest I do not sink I ‘ave to be worrying much,” she goes on in her normal tone, tightening her apron. “Most of ze demons (')oo come (')ere are not very bright, zey are not very interested in anysing except when zey are next banging zair bits together. Also I sink most mammals are (')aving trouble telling ze difference between male and female reptiles wizzout looking closely. Am I right?” She grins her long, meandering smile at you and you take her point.

¤Cumwitch (Ladysex) - Mispell
Planting a foot on her hip, you stop her fidgeting with a menacing glare. “You don’t get to fuck me, witch. I’m fucking YOU,” you decree. The well-endowed ganguro slut creases her pretty face into a frown, but meekly nods. Her pussy still seems puffy and wet, and her cock hasn’t shrunk at all. You sidle up and push a few fingers into her twat, testing the waters. As you expected, her fluids are as bountiful as most sand witch’s breasts. She squirms weakly at the attention, and her cock bobs happily on her belly. You affectionally pat the dark-hued member and playfully tug on her ebon (should be 'ebony') skin.

Uma (Talk > Loppe [the one about her first time]) - There's a mistake, a mispell and it didn't raise my lust.
-Second part-
Loppe nodded and continued to browse... until her eyes set upon a wonderful sight; a slice of carrot cake, fresh from the oven. Being part rabbit and part horse, two species known to love carrots, Loppe’s mouth instantly watered. She eagerly looked into her small purse, but she only had a few coins (I think it should be 'gems'), not nearly enough to buy the cake. Loppe sighed, well... best not dwell... maybe when she made it home her mother would be willing to reward her with some coins for her service?
...
-Third part-
“Oh, is that for me? Lovely! I love it! I want to take it for a test drive right now!” The wolfess giggles, falling back onto Loppe’s bed (should be 'her bed' not 'Loppe's bed') and spreading her legs wide to allow the laquine’s throbbing member easy access to her own plump, well-used vagina.
...
-Fourth part-
“No, nothing happened between then (should be 'them'). Puff wasn’t the type of person to take a girlfriend or have anything to do with anyone... she’s always been a free spirit in that regard. I mean, she wasn’t the only prostitute around, she was just the most notorious one. Being a nymphomaniac had a hand in that, I suppose. But back to the question at hand. Several days after Loppe’s little tryst with Puffy Lips I head an interesting bit of gossip from a client. I heard Puff had joined the local convent.” Uma grins.

**Comment by Fenoxo** [comment]
Fixt the latest one (though "ebon" is fine).
