### ISSUE TITLE
grammar/formatting in Benoit accepting wild basilisk eggs, 1st time - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#704]
The following is from the scene that results when a PC with Benoit's Basilisk Womb perk has eggs fertilized by a wild basilisk for the first time and lays. The below italicization is how it appears in-game.

“I see,” he says heavily. “<i>No, you were right to bring zem ere. Zey will be safe with me and 'ell knows I will need all ze eggs I can get if I am to make zis work.</i>” You breathe an inward sigh of relief and follow him into his shop.

(paragraph break is unnecessary) Benoit places the eggs into a blanket swaddled(should be hyphenated) basket with the same painstaking care he did with the others, before turning back to you.

The blind basilisk reaches out, finds your hand, and then squeezes it. “<i>[name], you must be more careful in ze future,</i>” he says. “<i>Please understand I am not saying zis because I am jealous or angry or anything</i>(should be 'anysing' in his accent)<i> so zilly. You 'ave done a great sing to change your body to 'elp my people, but if you keep getting attacked by my bruzzers and zey find out... if zey work out what you are... I do not like to sink about it.” You tell him you’ll be more on guard in the future and he seems to accept this. He gestures to the corner where he has put together a serviceable stove from scrap.

“Ungry?”(need italics and apostrophe in front to indicate omission of letter)

You linger long enough to share breakfast with him, and then return to camp.

**Comment by IndirectOne** [comment]
Those three mistakes should be fixed.
