### ISSUE TITLE
breast mismatch in incubus draft growth milestone - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#705]
The character in question was a hermaphrodite but had flat breasts and therefore no ability to titfuck. The text is reproduced below.

Your cock fills to its normal size and begins growing... Your arm-like, animalistic kitty-prick feels incredibly tight as a few more inches of length seem to pour out from your crotch. <b>Your meaty, spined shaft would look more at home on a large horse than you.</b> You could easily stuff your feline shaft between your breasts and give yourself the titty-fuck of a lifetime. Your cock feels swollen and heavy. With a firm, but gentle, squeeze, you confirm your suspicions. It is definitely thicker.

**Comment by IndirectOne** [comment]
Fixed. Was based on player being a herm. Now it checks that they have C-Cup or larger breasts.
