### ISSUE TITLE
non-printing character in camp Jojo's high-corruption meditation railroad - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#708]
PC had 79 corruption. Text also reuses 'approach' in the first sentence.

You approach the boulder where Jojo usually sits, and as soon as you’re close Jojo approaches you with urgency. [non-printing character]“<i>By Marae! [name], we must do something! I feel the corruption surrounding you like a dense fog. We need to meditate or I’m going to lose you!</i>” Jojo pleads.

Do you accept Jojo’s help?

**Comment by IndirectOne** [comment]
Got it. Changed 'approach' to 'walk toward'.
