### ISSUE TITLE
grammar/ellipsis abuse in camp Jojo's high-corruption meditation railroad acceptance - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#709]
Occurs when a PC with 10+ corruption approaches Jojo in camp, is asked to meditate, and agrees.

Original text:

“<i>Thank Marae, you’re much stronger than I my friend... to hold so much corruption and still retain your will.... But let us not tempt fate,</i>” he says before the two of you get to it.

Suggested text:

“<i>Thank Marae. You’re much stronger than I, my friend, to hold so much corruption and still retain your will. But let us not tempt fate,</i>” he says, before the two of you get to it.

**Comment by Frahuenheld** [comment]
I always thought that Jojo has asma.

**Comment by IndirectOne** [comment]
I left in the one set of ellipses after friend, but otherwise changed it to what you suggested.
