### ISSUE TITLE
'using' armor materials from inventory consumes them - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#710]
If the PC attempts to use black chitin, green gel, or tough spider silk from the inventory, the messages suggest bringing it to a craftsman instead, but the item is consumed regardless.

**Comment by IndirectOne** [comment]
Yeah, that bug was reported and fixed a while ago. I can't remember if it's been merged into CoC-Alpha yet, but it may already be fixed there.

**Comment by Fenoxo** [comment]
Seems to work more or less fine in the current code I've got (at least for green gel)
