### ISSUE TITLE
defeated imp's 'Female Fuck' option is available to Feeder PCs regardless of lust - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#711]
Non-feeder PCs must meet the minimum lust threshold to make the choice appear. The 'Male Fuck' option is unaffected by the bug.

to reproduce:
-make a female PC
-induce lactation
-raise corruption over 30
-obtain 'Feeder' perk
-defeat an imp with < 30 PC lust

**Comment by Frahuenheld** [comment]
NippleFuck is unaffected too.

**Comment by IndirectOne** [comment]
That one was tricky. A whole block of code got bypassed if you were not a feeder. Rewrote the impVictory() function that handles this, should solve both feeder and nipplefucks.
