### ISSUE TITLE
Bug on Kiha's Affection

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#712]
Well, it's not a bug but more like an error. This happens when you visit her at the Swamp after having the "love hug" and she cooks you. If you chose the "It's Good" option then the sex menu pops with every sex option and the "Back" button. Choosing Back you're brought again to every possible activity with Kiha and by clicking "Hang out" you can gain extra points in affection. I even got 25 points in just one visit thanks that the meal scene popped four times in a row.
My recomendation is to code it so when you have the meal scene you only have the "Next" button which shows a random sex scene from the ones you have available.

P.S: Sorry if my english is bad.

**Comment by IndirectOne** [comment]
Fixed it so that you don't have a back button if you're coming from "It's Good". Instead you have an option to leave.
