### ISSUE TITLE
Arian scenes

### ISSUE THREAD

**Issue by Frahuenheld** [herp-a-derp/Corruption-of-Champions#713]
I have been dating Arian lately and used a lot of variables in search of bug or typos but the most remarkable thing so far are the pronouns in his changing gender scenes. In the scenes his pronouns sometimes stick to the former gender making it very confusing.

**Comment by IndirectOne** [comment]
Any chance you could list them? Trying to locate them in code is difficult with Arian because it's all tied into the parser tags.

**Comment by Frahuenheld** [comment]
Ok, I will.

**Comment by Frahuenheld** [comment]
¤Arian (from herm to male) - Besides the  mispells and the part were they talk about egg-laying, the fact that he became fully male with Incubi Draft is not lore-wise. When you talk with Urta about the law in Tel'Adre she mentions that you can't do that.
Fishing around in your pockets, your hand closes on the vial of purified incubus draft. You offer this to Arian, asking if she would like to make her cock bigger.

Arian blushes. “I don’t mind the way I am now, but if you want me to take it I’d be happy to.” Arian smiles nervously at you.

You tell her that you would like her to take it, and hold it out to the lizan with greater emphasis. Arian takes the draft, uncorks it and chugs it down.

Arian shudders as she feels the changes sweep through her, but rather than settling on her huge lizan shaft, the warmth that precedes change settles on her breasts. Arian moans and kneads her mounds as they shrink until they are completely gone. Her nipples follow suit, being replaced by smooth scales.

Arian moans as another change happens below; she spreads her legs and watches in wonder as the lips of her wet fuckhole join together, becoming smooth scales as well. A few more subtle changes occur as Arian’s body shift towards the masculine and finally settles down. Arian breaths a sigh of relief.

“I guess I’m male now?” Arian’s voice sounds more masculine as well.

You note that seems to be the case. So, is she (he) going to miss being even half-girl? Arian rubs her (his) chin. “Well, it was weird, but it was kinda nice too.” She (he) looks at you, smiling nervously. “I’d spend some time in the mornings looking in the mirror. I guess I didn’t look so bad as a girl?”

You note that she (he) was quite pretty, but you think she(he)’s just as handsome now. Besides, being all-guy means no more dealing with eggs, right?

Arian blushes, averting her (his) eyes in embarrassment. “It wasn’t that bad... the whole deal with the eggs I mean.”

He can really say that? After actually going through the painful process of laying them? Because, if she (he) can, well, you think you’d have to call Arian one of the manliest men you’ve met in this world. 

Arian smiles at you. “It didn’t hurt that much.” Then she (he) blushes. “It felt kinda nice... actually.” (These last three paragraph should only apply when Arian has actually laid eggs. In my case, he didn't).

You just shake your head and clap him on the shoulder. Well, maybe you’ll give him her (I don't know which gender would apply better) vagina back, if she (he) really didn’t mind being half-girl that much. But, right now, you think she (he) should try and get used to being all-man again.

Arian averts her (his) eyes. “Of course. If that’s what you think.”

You reply that is what you think. So, does she (he) feel up to doing anything else, or should you leave him to get some rest?

Arian’s cock begins hardening. “Well, I wouldn’t mind doing anything else... if you want to.”

¤Arian (from male to herm) - I changed the first pronouns (sorry @IndirectOne xD) to male because Arian would become a trans/newhalf just after the growth of the tits. Also, I added a variable for when he is in the camp so feel free to add if you like it :3
Fishing out the bottle of purified demon’s milk, you ask if Arian is willing to get in touch with his feminine side. For you?

Arian bites his lower lip. “For you? Of course I wouldn’t mind it.” You pass over the bottle, and watch as he removes the cork and drinks its contents.

Arian gasps and moans, a throaty, girly moan. She (he) opens her (his) robes to watch as the changes sweep through him. First the smooth scales of her (his) chest begin flaking off, making way for a pair of erect nipples; following the growth of said nipples, her (his) previously flat chest begins inflating, growing into perky scaly breasts. Down below, Arian feels a wave of heat gather between her legs; once she spreads them, she gasps. A slit appears, the surrounding scales become smaller and softer, forming what looks like a tight little pussy. Arian’s newly formed labia puff up and juices begin flowing freely from the moist passage, even as Arian’s little pleasure buzzer appears to slightly part her labia in a clear invitation for you to explore its depths.

You drag your eyes away from Arian’s new vagina and look the newly hermified lizan in the eyes, asking if she feels all right. Arian pants, questing hands wandering towards her breasts to gently grope them. “Hot... so hot...” Arian’s shaft hangs fully out of its hiding place, rock hard and throbbing.

You tell her you’ll get her something cold to drink, turning towards the door. “H-hurry, please!” You need no further encouragement and quickly race to the kitchen, where you grab a jug of water from the coldbox and run back with it, as quickly as you dare. (Variable for when Arian's in the camp: You tell her you’ll get her something cold to drink, turning towards the exit. “H-hurry, please!” You need no further encouragement and quickly race to your tent, where you grab a waterskin and fill it in your barrel of water [if Kid A is in camp: avoiding to hit Kid A in your hurry] before running back to Arian's tent.)

As soon as you enter Arian’s room, she sweeps the jug from your hands and begins downing the water. You watch in amazement as Arian drains the jug of all its water, some stray droplets falling on her exposed scales, forming small rivulets that trace Arian’s increasingly feminine curves. Once Arian is done she sighs with relief, quietly handing you the jug and wiping her lips with a forearm. “Thanks, Seizobaru. I really needed that.” Arian smiles at you, no longer hot to the point of boiling. Her previously erect cock having already softened and retracted as far as it’ll go into its protective slit.(Variable for when Arian's in the camp: As soon as you enter Arian’s tent, she sweeps the waterskin from your hands and begins downing the water. You watch in amazement as Arian drains the waterskin of all its content, some stray droplets falling on her exposed scales, forming small rivulets that trace Arian’s increasingly feminine curves. Once Arian is done she sighs with relief, quietly handing you the waterskin and wiping her lips with a forearm. “Thanks, [name]. I really needed that.” Arian smiles at you, no longer hot to the point of boiling. Her previously erect cock having already softened and retracted as far as it’ll go into its protective slit.)

You cautiously ask if Arian is feeling okay; she’s just undergone quite the dramatic change. Arian looks herself over, running her hands across her newly feminized body. “I guess I’m fine. I certainly feel fine, at least.”

You can’t help noting she looks pretty fine, too. Arian blushes at your comment. “Umm... thanks.” One of Arian’s questing hands find her newly formed slit, and she gasps in pleasure as she circles her soft labia with a clawed finger, smearing some of her juices on her finger. She lifts the finger to her face and watches the moisture drip from her digit; then, without sparing a thought, she takes the finger into her mouth and begins lightly sucking on the digit.

You pointedly cough and tell her that, while you’re not necessarily minding if she wants to try out her new body, does she really want to put on a show for you, or would she rather you leave? Arian snaps out of her trance, blushing in embarrassment. “Oh! Sorry!” Arian attempts to cover her breasts and crotch with her arms. She fidgets a bit, then smiles nervously at you. “Umm, maybe you’d like to help me get used to my new body?” Arian averts her eyes, blushing furiously at what she just said.

You step forward and gently run your hands over her newfound breasts. Well, if that’s what she’s in the mood for, you’re game.

¤I think that Laika should react too when Arian become a herm in his house like when he becomes a female using his Pink Egg Elixir.

**Comment by Fenoxo** [comment]
Not doing the extra stuff you tried to add, but gender flags should properly change mid-scene now.
af1e071b520e17f22e0a671750724c4ed16ce2a1
