### ISSUE TITLE
Sophie morning scene happening after first exploration

### ISSUE THREAD

**Issue by The-Art-of-Futility** [herp-a-derp/Corruption-of-Champions#714]
I am using what I assume to be the latest version of CoC, as it is the one posted on Fenoxo's site. After sleeping, I am given the usual interface: explore, places, inventory, etc. however, after one I perform an activity like exploring or going somewhere and thereby passing time, upon returning to camp I am met with the Sophie morning scene : "As you're waking up that morning... " etc. etc. It's not a major problem, however it certainly is a bug, and therefore worth mentioning. I'm not sure what else I should say, though I suppose you have ways of notifying me if you need more info.

Thanks for the hard work.

**Comment by IndirectOne** [comment]
I've checked it on 0.9.2 (the version on Fenoxo's site) and it happens at 6:00 each morning for me. The code for it actually tests specifically for model.time.hours == 6, so it should be impossible for it to trigger at 7:00am. No idea how this is happening.

**Comment by Fenoxo** [comment]
No further information for months? BUG DED
