### ISSUE TITLE
missing space in Lake big cock bondage percing scene - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#716]
The impending erection can’t seem to be stopped. Your sexual frustration forces stiffness into your two giant, mutated dicks, which forces your torso to the ground. Normally your erection would merely raise itself skyward, but your genitals have grown too large and heavy for your wide hips to hold them aloft. Instead, you feel your body forcibly pivoting at the hips until your torso is compelled to rest face down atop your pair of giant, mixed cocks. Your <b>ceruleanballsack</b> rests beneath your raised slappable, thick rump. Your pair of beachball-sized gooey balls pulse with the need to release their sperm through your two monstrously thick, mixed cocks and into the waters of the nearby lake. Your moist cooter and greedy clit are thoroughly squashed between the bulky flesh where your male genitals protrude from between your hips and the spacious, cushy ass above.

**Comment by IndirectOne** [comment]
Ok, fixed.
