### ISSUE TITLE
Cock-Exgartuan 'too many hours since cum' dream happens in daytime and while Exg is asleep - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#718]
Cock-Exgartuan's too many hours since cum dream triggers during the day, not after any sex or nap, and can even trigger while Exgartuan is 'asleep'. The text explicitly states that the dream should be occurring at night only. Easiest to observe by manipulating S. Delite to increase hours since cum rapidly.

To reproduce:
-achieve high cum volume with M or H PC (3500+mL in test case)
-enlarge cock
-acquire Cock-Exgartuan
-obtain S.Delite(s)
-use S.Delite until you get the effect that increments hours since cum one or more times (45000+mL cum volume was observed at this point)

Opening paragraph of dream scene reproduced below (with grammar note):
Something interrupts your relatively peaceful sleep midway through the night. Once pleasant dreams shift and morph towards<i>(should be 'to')</i> nightmares in a heartbeat! You’re gagging, choking even, and no matter how you twist and struggle you can’t breathe! Spikes of terror jump-start your heart and propel you back to wakefulness at breakneck speed. Your eyes snap open and you try to sit up, but pain lances through your groin and throat, holding you in position. Completely panicked, you look as far down as your restricted vision will allow and recoil in horror. The bulging, veiny mass of your reptilian shaft is lodged deep in your throat, arching and twitching hard enough to slide itself in and out with gentle half-strokes.

**Comment by IndirectOne** [comment]
Alright - all fixed. Looks like I missed the time check long ago when moving this stuff out of dream.as.
The check for whether or not Ex. is asleep, however, was missing from the cock version but not missing from the boob version.
