### ISSUE TITLE
multi-breast display and multi-cock display formatting in Appearance screen - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#719]
The dashes used to list multiple breast rows and multiple cock rows in the appearance screen do not match.

Example:
You have two rows of breasts, the topmost pair starting at your chest.
—Your uppermost rack houses [...]
—The second row holds [...]

Where a penis would normally be located, you have instead grown two ready, bulging snake-dicks!
-Your first inhuman cock is [...]
-Your next bulbous snake-shaft is [...]

**Comment by IndirectOne** [comment]
I am assuming the use of the long dash for breasts was deliberate, so I changed the cock descriptions to match.
