### ISSUE TITLE
grammar/italics in Cock-Exgartuan beegirl surprise sex - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#720]
Scene in question happens occasionally when Cock-Exgartuan is awake and PC encounters a bee-girl. Internal dialogue is still dialogue and should have double quotes and italics.

“<i>You sure know your knots! Speaking of knots, I got an idea...</i>” exclaims the demon inside your serpentine shaft. 'What has he got in mind this time?' you wonder as you finish spreading the bee-bitch’s legs in preparation. The scent wafting out from her genitals is unreal, making you simultaneously hungry and incredibly horny. You pull up the ginormous flanged tip with both hands and rub it over her honey-slicked crotch, mixing your demonic pre-seed with her honey as you smear it all over her downy inner thighs.

**Comment by IndirectOne** [comment]
I'm not sure about that. There are several places in the game where the player thinks something to themselves and single quotes and non-italicized text are used to indicate that this is different and not being spoken aloud.

**Comment by Zeikfried** [comment]
Honestly, you could nix the whole sentence. It ascribes naiveté to a character who's drank so much cock serum that his schlong is big enough to host another soul and then seen that soul do horrible things.

**Comment by Fenoxo** [comment]
Fixt 5c0cb753030adaf6cdece712bdf25d4c24b8141f
