### ISSUE TITLE
Cock-Exgartuan's armor change notification printing multiple times per hour, re-printing at semi-random intervals - 0.9.2

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#721]
Sample of text is below. Upon first activation, the text printed and then again in the subsequent line. It also prints two to three times per night-day cycle, seemingly apropos of nothing.

<b>The miniscule piece of swimwear that doubles as a tent to your canine shaft begins to grow and encapsulate it, molding itself perfectly to your manhood. You pivot your hips forwards, doing your best to show off your sensational package with every step. Oh, very nice, you’ll have to thank Exgartuan later...</b>

**Comment by IndirectOne** [comment]
Tricky. But it should now be fixed. Exgartuan's code wasn't testing whether or not the armor was already bulged, only whether it could be bulged.

**Comment by Zeikfried** [comment]
It also seems to add a new copy of the perk for each printing, so you may need code to remove those extras.

**Comment by Zeikfried** [comment]
Notifying @IndirectOne of perk spam now that he's back.

**Comment by IndirectOne** [comment]
I'll mess with that once I've reached a good point in the Kath expansion - where things compile, for example :)

**Comment by Fenoxo** [comment]
Assuming IndirectOne's fix handled it proccing multiple times, I've put in a safeguard against multiple stacks of perk. Closing e32a9cf68bd135b335612a3ad7b24efa672405ff
