### ISSUE TITLE
Rubber Fetish Clothing

### ISSUE THREAD

**Issue by Terminator78** [herp-a-derp/Corruption-of-Champions#722]
Mmhh.... Don't know how to make this post long and dramatic but it's a bug report so f+++ it...

Rubber Fetish clothes....when I read it upgrades tease to seduce it was clear I needed it on one of my nine characters. But when I bought it I discovered that there was no visual change in the tease ability, no feedback at all. And secondly, every other armor I wanted to equip(Slutty Swimwear, Chaimail Bikini, Bee armor, something else I can't remember) was automatically renamed into reavealing rubber fetish clothes both in the inventory aswell as in dialogues. The defense stats however changed with every armor.

hope this helps and PS, I'm using the android version.

**Comment by Fenoxo** [comment]
Fixt the tooltip to be more clear. It gives you a perk that boosts your tease attack. It doesn't rename the tease attack or change the texts.
