### ISSUE TITLE
2 Problems with Katherine and a Main menu issue

### ISSUE THREAD

**Issue by bushitakagi** [herp-a-derp/Corruption-of-Champions#725]
First primary issue: Kath won't accept some of the items that I think she should. Namly she wouldn't accept just a basic canine pepper to change her cat cock back into a dog cock, I had to use one of the other types of canine pepper because that pepper wouldn't show up in the menu as something to give her. I also can't provide her Reducto and since that's the only way to shrink her knot for +1 Submissiveness (regrow knot, if you can't reducto it, then you can't regrow it), +3 Submissiveness causing the castration (you have to reduct the balls down to 1", and then use both a Reducto and a pink egg to be rid of the testicles, 
Because it doesn't allow you to use Reducto properly you also can't change her body back to normal from the following: +2 Submissiveness on lowering her breast OR cock size back to normal, +4 Submissiveness changing the testicales back to pre-expansion sizes,+6 Submissiveness Remove and Regrow a cock since you can't shrink it to be rid of it. I don't know what other items she won't accept, but those two at the very least. Reducto shows up in the menu, but when you click on it it removes all the text in the text box (what's going on in the story at that time), and it doesn't bring the menu up for what items should be reducted. I can use it on the PC just fine.

ISSUE 2: Another issue with Kath though much more minor: If the PC is female and is penetrated by her, the PC keep its virginity. My PC had sex with her 2 or 3 times (in the text it even stated she came inside of my PC's womb once) but the PC was stilled listed as a virgin and within the text of the sex act it never stated the PC lost her virginity. When the PC had sex with the gargoyle later on, it stated there was a ripping of the hymen and that the PC lost her virginity in the sex text and within the stat text.

ISSUE 3: Last but not least a main menu problem. When you open the game again (I play from a download onto my PC), the settings change bad to defaults it seems. I changed settings and started my game, just now checking what was and wasn't on, I had to remember what my settings where because they were back at defaults. When I reloaded my save, the default settings from when I was checking the menu (I didn't touch any of the options) were enabled in the save instead of the settings that I put on when I started that save in the first place.

All this being said:
I'm using the most current build: "Corruption of Champions (0.9.2-A-249611a (Moar Bugfixan))"
I met Kath without meeting Scylla, met her as her gang robbed me, I also already went through getting her a job (obviously).
The settings I started my game with were: EZ on , low standards on, silly mode off, hyper happy on. I'm also playing as a 100% pure character. I've had anal sex with Izma a few times to get her into the camp, lesbian and 69 sex with Phylla once each, lesbian sex with amily once, tail sex from the gargoyle once, blowjobs and a few jerkoffs on the PC's face from Urta, a bunch of training sex in the lake, lots of handjobs, a couple blowjobs, and sex 2 or 3 times with Kath. My PC was never violated by any of the mobs or anything. Just in case any of that stuff matters.

I wanted to max out her submissiveness and each time I was to go up a level by changing her body, I wanted to change it back to what it was previously. It stated in the wiki, that changing Kath's body back to how it was previously without effecting the submissiveness level negatively.

Those are the only issues I've found besides for a few spelling mistakes (I've been playing this game for over 24 hours real time so far).

**Comment by IndirectOne** [comment]
Ok, issue 1: No, she doesn't accept regular peppers. That's something that got cut because I wanted to push the expansion out the door. It would make sense. Reducto is another story. She currently has no restrictions on reducto - no idea why that's not happening. And I've used it in testing recently and seen it work.

Also, the wiki is correct. You can change her every which way to increase her submissiveness and then back to her original form. And I tested to make sure you can do it without being corrupt (though that does make things easier).

Issue 2: Tested this - saw warning she'd torn my character's hymen first time. It is possible all those options you have turned on are preventing things from working properly.

Issue 3: I'm willing to bet that stuff is never getting changed. I've never really looked at it but it seems reasonable that the settings all start at default values when you open the game.

**Comment by bushitakagi** [comment]
Should I provide a save so you can try and see what's blocking the reducto?

**Comment by IndirectOne** [comment]
Sure, but first try talking to her with the game at default settings. See what happens.

**Comment by bushitakagi** [comment]
Did, it's in the 'give item' menu but when I click it it just clears the text from the main area and it doesn't bring up the little menu that tells you what can be shrunk :-/ I was really hoping that just putting everything to default would work.
Save is as follows:
http://www.mediafire.com/download/4z7kne0lc85gav6/CoC_1.sol

I'm not sure if it was saved with defaults on or not. You have to go to and from tre'adre I think 2-3 times before Katherine shows up at that bar. Asking for a date then destination her house allows you to go there and give her items. There is a reducto in your inventory already and I think one of the canine peppers I think it's the one to make her balls bigger or something.
I'm on a Win7 PC so hopefully that isn't the problem.

**Comment by IndirectOne** [comment]
Interesting. I'm not sure why it isn't working with that alpha build. It is working in both an older alpha build I had and in the official 0.9.2 release. I suggest you load the save in the official release, use the reducto and go from there.

**Comment by bushitakagi** [comment]
This is going to sound stupid but I got the one I'm using from here just the day before I posted this, the CoC Alpha, is that not the proper one? If not then were do I get the proper one?

**Comment by IndirectOne** [comment]
CoC-Alpha is usually better, but the official current release is on fenoxo.com under the play tab.

**Comment by herp-a-derp** [comment]
CoC Alpha is a version automatically built from the latest source code changes. 

This means it's it's the most up-to-date version possible, but it also means that it's possible there are new bugs that have not been caught yet, particularly if there are major changes (or the BuildBot has shat a brick).

**Comment by bushitakagi** [comment]
Ohhhhhhhh.I thought the one at Fenoxo was old, since he linked here I figured he was done with everyone on his side and just left it open to everyone else to tinker with. Okay then I'll go download it from there then lol.

**Comment by IndirectOne** [comment]
That's fine. Just right click on the download, save link as, pick a folder on your hard drive. Then type c: in the firefox address bar and navigate to the folder you saved the swf in.

For an easy way to transfer a save first open the copy you already have, click "Save File" instead of "save" and then save it in the same folder as your downloaded swf. That way you can open it easily in the newly downloaded copy of the game.

**Comment by bushitakagi** [comment]
:-D thank you. I've found that for some reason even in the one I got from there that Katherine won't allow me to remove her dick she says she was born that way and asks if I understand why she doesn't want to lose it. I have her submissiveness up to 7, which I didn't even realize it went that high. I've done everything to her that can be besides the ones that require corruption or tenticle dicks (if there's an option for those). the only new thing I can do at this point is remove and regrow the cock, neither of which I can do if she won't eat the pink egg. Beyond that everything's been going pretty good.

Though I have a question about Helspawn does anyone know her editing information? I mated with Helia (and I'd like to stick with that option), but I'd like the black scale child which I presume (from the wiki) can only be obtained from Helia mating with the spider. Is there a way to mod her with the CoCEd (I think that's the one only available to windows users). I've found a few lists of all the different items that exist that can be edited, but there isn't a list of available choices (cause some require long strings of numbers instead of a simple -1,0,1 or 0,1,2 option), what the numbers may do for those long strings, or even what all the items actually do when you modify them, which isn't surprising considering the mass of ones listed as unknown flag.

**Comment by IndirectOne** [comment]
The option to feminize Kath was only added in after the most recent release.
It requires submissiveness 6+ and might be in the current CoC-Alpha build. Of course once you use that you'll be stuck with CoC-Alpha as the older code for Kath won't interpret things correctly if she has no cock.

**Comment by bushitakagi** [comment]
ahh that explains it, well damn, after that issue with reducto and kath in the Alpha I think I'll stay away from it for a while til more of the bugs get removed :-(.

Hopefully one day you can build like a giant manor or something with the portal inside it or some such thing and have room for all your children and lovers in it >.> <.< would love to have the gargoyle, urta, and katherine at camp, they're my fav 3 so far seriously starting to like helia too and Izma is growing on me quiet fast.
