### ISSUE TITLE
Marble talk bug

### ISSUE THREAD

**Issue by wyvvern** [herp-a-derp/Corruption-of-Champions#726]
Noticed this because someone made a comment on the forums. In MarbleScene.as there's this:
```
	else if(flags[kFLAGS.DISCOVERED_DUNGEON_2_ZETAZ] < 0 || player.statusAffectv1(StatusAffects.TelAdre) == 0)
		outputText("\"<i>Well sweetie, maybe you should explore the world more?  From what I've heard from the centaurs who stop by the farm, I'm sure you could find something interesting in the deep forest, or maybe the desert,</i>\" she suggests.");
	//(suggestion) If PC has found Tel'Adre, but not Zetaz's lair(Z)
	else if(flags[kFLAGS.DISCOVERED_DUNGEON_2_ZETAZ] < 0 && player.statusAffectv1(StatusAffects.TelAdre) >= 1)
		outputText("\"<i>I was thinking that the deep woods probably still hide secrets from you, sweetie... a few times I've been there, I've noticed large numbers of imps carrying supplies.  Think there could be something to that?</i>\" she asks.");

```
both the flag < 0 checks need to be changed to == 0. That flag is never decremented in code, so the logic makes zero sense. The first check might print because it's a logical OR but the logical AND can't ever be passed as coded.

TDM also suggested adding this to her dialogues for D3:

""Well [playerName], this is it. Your mission has been to stop the demons, Lethice is their leader. Once you're ready, you need to go to their high mountain lair and take them down. Make sure you've finished everything else you want to do before you face Lethice, you won't get a second chance.""

Could probably just replace her "Sweetie, you've finished all that there is in the main story of the game so far.. . ." block with that and keep the logic intact.

**Comment by Fenoxo** [comment]
Fixt
