### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by liam-middlebrook** [herp-a-derp/Corruption-of-Champions#730]
First, the standard disclaimer: I am not a lawyer, and this does not constitute legal or financial advice.

Generally, IMHO, it is a good idea to use FSF or OSI Approved Licenses (which can be found here https://www.gnu.org/licenses/licenses.html and here http://opensource.org/licenses/category)

The Free Software Foundation has a useful guide for choosing a license: https://www.gnu.org/licenses/license-recommendations.html

I often reference the Software Freedom Law Center's Legal Primer for both practical and academic purposes (highly recommended): https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-60002.2

https://tldrlegal.com/ is quite a useful resource for comparing the various FOSS licenses out there once you have some context

To get ahold of actual lawyers/advisors who help FOSS projects, you can reach out to the FSF, SFLC, and OSI at:
licensing@fsf.org
help@softwarefreedom.org
license-discuss@opensource.org

Hope this helps, and happy hacking!

**Comment by herp-a-derp** [comment]
Uh.... I'm going to assume this was an auto-post, because there is clearly license information in the readme.

If not, it was a stupid post.

**Comment by Thirsk** [comment]
>there is clearly license information in the readme
When was the last time you took a look at the readme? Because there is no license anywhere in it. In fact, there has never been a license anywhere it in at any point it time. 

The readme is this verbatim:
> Corruption-of-Champions
> =======================
> 
> NOTE: CONTAINS MATURE CONTENT. ADULTS ONLY
> 
> CoC source from Fenoxo.
> Modifications by everyone at:  
> https://github.com/herp-a-derp/Corruption-of-Champions/graphs/contributors
> 
> Check out the wiki for information and the FAQ.
> 
> Everything is copyright Fenoxo (fenoxo.com).
> 
> **This repository is the game source-code only**
> 
> Latest builds (e.g. an actual, playable version of the game) are generally available in the CoC-Alpha repo:  
> https://github.com/herp-a-derp/CoC-Alpha  
> Note that these are alpha-quality builds, and likely may have bugs and other fun easter-eggs.

**Comment by JustGregory** [comment]
I think maybe Fenoxo was thinking the 2nd, 3rd, and 6th lines of text sufficed for license; at least, that is what I am presuming he meant by those lines...
