### ISSUE TITLE
"Bondage Patient Clothing" Bug - Stuck on with no way to unequip

### ISSUE THREAD

**Issue by anonsyd** [herp-a-derp/Corruption-of-Champions#731]
My character lost a fight to a fetish cultist, and as a result got put into the bondage hospital scene.

I didn't pay much mind and played on, saving afterwards. However now there's a weird bug where it considers me having the "bondage patient clothes" permanently equipped. At least I assume it's a glitch, I can't find any reference to it anywhere as far as it being a permanent punishment curse sort of thing.

Basically in the inventory screen, it says Armor : bondage patient clothes, but it also somehow considers what I actually equip in regards to armor and perks, like giving me armor for wearing plate and wizards endurance for wearing the wizards robe. However, when I go to Tease, one of the potential teases relates to the bondage clothes, so it isn't entirely superficial.

Unfortunately, as much as I try save editing, I can't exactly figure out a way to completely unequip these, and so I'm frustratingly stuck. Any help would be great.

**Comment by IndirectOne** [comment]
Yes, this is a known issue and has been corrected. Just waiting for the next release.
As for fixing through save editing you can do that by setting saveFile.data.armorName to an empty string. That will allow the armor ID to set what you're wearing.
