### ISSUE TITLE
Kid A Weapon Bug

### ISSUE THREAD

**Issue by twinkypinkie** [herp-a-derp/Corruption-of-Champions#732]
If you have Kid A in your camp, you are unable to give it a weapon. If you try to give it a weapon when there is no weapon in your inventory, things appear normally (the "back" button is the only option available). If you DO have a weapon and click to "Give Weapon", all the buttons disappear on the next page, including the "back" button. This renders all of the Kid A content once in your camp unattainable.

**Comment by IndirectOne** [comment]
Yup. Known bug and it's already been fixed. Just haven't seen a new release since then.

**Comment by Fenoxo** [comment]
Seems to be the case.
