### ISSUE TITLE
Rubi blank screen

### ISSUE THREAD

**Issue by ghost** [herp-a-derp/Corruption-of-Champions#733]
Basically when you go to Rubi's place and click closet, you can get past the next text screen but then the one after that is completely blank with the option to click next, but that doesn't do anything, so you are basically stuck and have to reload your save.

**Comment by Kitteh6660** [comment]
I did some testing in FlashDevelop and here's what I've found.

It has something to do with that line: https://github.com/herp-a-derp/Corruption-of-Champions/blob/master/classes/classes/Scenes/Places/TelAdre/Rubi.as#L118

**Comment by Fenoxo** [comment]
Fixt
