### ISSUE TITLE
Lethice's Stronghold

### ISSUE THREAD

**Issue by badss22** [herp-a-derp/Corruption-of-Champions#735]
![capture](https://cloud.githubusercontent.com/assets/11968329/7169233/3c8be7a2-e389-11e4-90d4-f30d1a5bc603.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/11968329/7169237/3ebccd02-e389-11e4-8205-a8bfd55dac50.PNG)
![capture 3](https://cloud.githubusercontent.com/assets/11968329/7169238/40398b02-e389-11e4-9a60-f45c73349a5b.PNG)
 these are pictures of my desktop from when i am in Lethice's Stronghold. i have beaten the doppelganger and just outright smashed the mirror and i didn't go to the hall before i beat him. it is as you can see in [capture 2] and when i click go nothing happens it acts like i didn't click it nothing happens even if i click it a hundred times the only thing that happens is when i click Fall back and it brings me to the screen on [capture 3]. i am playing it from your website and i left click on the download link and it brings me to the link as you see and thats how i play.

**Comment by Fenoxo** [comment]
Can I get a copy of your save to test with?

**Comment by badss22** [comment]
How do I go by doing that? I am playing the browser version

**Comment by Fenoxo** [comment]
Save to file, then upload the file somewhere and link it to me.

**Comment by Fenoxo** [comment]
Or if you have trouble with that, send it in an email as an attachment to fenoxo@gmail.com

**Comment by badss22** [comment]
i sent it as an attachment to your gmail

**Comment by Fenoxo** [comment]
Thanks. Got it and fixed it for a patch. It'll be on the site in a few minutes

**Comment by Bruh1326** [comment]
Same thing happens on mobile. Patch?

**Comment by Master-Death19** [comment]
If you don't take the glasses you can proceed to battle the basilisk leader in the hall, but if you messed up and took them you just get a blank screen as shown above with the mobile app version.
