### ISSUE TITLE
Magpie Hall Error + Missing Horned Rubi sprite

### ISSUE THREAD

**Issue by Kitteh6660** [herp-a-derp/Corruption-of-Champions#737]
I've found the code that causes the game to crash if you have Laybans and press "Go!"

It's missing outputText!
https://github.com/herp-a-derp/Corruption-of-Champions/blob/master/classes/classes/Scenes/Dungeons/D3/JeanClaudeScenes.as#L36

In addition, horned Rubi sprite never appears.
https://github.com/herp-a-derp/Corruption-of-Champions/blob/master/classes/classes/Scenes/Places/TelAdre/Rubi.as#L72
This is because that line of code is ALWAYS executed each time the sprite is called for. Adding 'else' will fix that.

**Comment by Fenoxo** [comment]
Ah yeah, I already fixed the magpie hall crash, just forgot to push.

**Comment by Fenoxo** [comment]
Rubi sprite fixed via bdc17dbee0f2b039396e6662dc98362ed05139fd
