### ISSUE TITLE
Selecting Closet while talking to Ruby soft locks

### ISSUE THREAD

**Issue by notKyll** [herp-a-derp/Corruption-of-Champions#740]
Ruby asks if you want him to wear something, and then all text is gone and only a non-functional next button is displayed

**Comment by Fenoxo** [comment]
What version of the game is this with? I was unable to replicate this in 0.9.4c

**Comment by notKyll** [comment]
I have realized that I was on v0.9.4 and the bug seems to have been fixed as of 0.9.4c
