### ISSUE TITLE
Tower of Phoenix, unable to finish

### ISSUE THREAD

**Issue by Promenius** [herp-a-derp/Corruption-of-Champions#744]
I finished the Tower of Phoenix dungeon (taking Valeria, the God's Mead, the torture equipment, etcetera) and let the Harpy Queen go. But, when I try to release Hakon, the game just reverts back to the Phoenix Dungeon scene before I let him go. 

Time passes two hours forward whenever I try to release him, but it refuses to move on with the storyline, and simply places me back in the dungeon, where I can try to release Hakon again but with no effect; it simply loops! Over and over, despite having both keys to release Hakon!

**Comment by IShipItAll** [comment]
I'm having this same problem. I have no idea what to do

**Comment by IShipItAll** [comment]
Help.....

**Comment by Fenoxo** [comment]
Which version of the game are you playing? I could've sworn this was fixed...

**Comment by IndirectOne** [comment]
Just tried it in 0.9.4c. I can confirm that it works properly there.

**Comment by IShipItAll** [comment]
0.9.4 (Moar Bugfixan)

**Comment by IShipItAll** [comment]
http://www.fenoxo.com/playCoC/CoC_0.9.4.swf

**Comment by IShipItAll** [comment]
![akuma](https://cloud.githubusercontent.com/assets/12207871/7448964/42d766d2-f1de-11e4-8f8c-521b4776bf30.JPG)

**Comment by IShipItAll** [comment]
over and over

**Comment by Fenoxo** [comment]
Try playing the actual latest build, http://www.fenoxo.com/playCoC/CoC_0.9.4c.swf

Not sure why you're on an old version.
