### ISSUE TITLE
0.9.4c Mountain Factory is not available after visiting it once

### ISSUE THREAD

**Issue by DancingDerwish** [herp-a-derp/Corruption-of-Champions#746]
I had this bug now twice, exploring the mountains after talking to the goddess in the lake anf finding the factory, the first time I leaved straight away, the second time I went inside but only managed to get the secretary. In both cases the factory wasn't available under 'Places' nor could it be refound at the mountains...

**Comment by Fenoxo** [comment]
It appears in the "dungeons" submenu. I've fixed the notification to be more accurate.
