### ISSUE TITLE
Female Latexy and Incubus Draft bug? problem?

### ISSUE THREAD

**Issue by assassin0223** [herp-a-derp/Corruption-of-Champions#752]
Having female Latexy use an Incubus Draft has a problem. I get the scene and after pressing "Next", I am not returned to where I was before. The text disappears and pressing buttons doesn't do anything. In the end, I am forced to restart the game.

That doesn't happen w/ Female Latexy and Minotaur Blood.

Doesn't happen w/ Herm Latexy and an Incubus Draft.

I found that this happens in CoC_0.9.4C_mod_1.2.8.swf.

Hope this helps.

Edit: this is embarrassing, this was going to be for coc mod, not vanilla coc.

**Comment by Milobe115** [comment]
Also appears on 0.9.3 vanilla.

**Comment by Fenoxo** [comment]
I don't make the mod, and I'm pretty sure we already fixed this in the main game.

**Comment by Gedan** [comment]
Yup, tested this based on another report just now and it seems to be working just fine so w/e.
