### ISSUE TITLE
tentacle beast missing capitalization - 0.9.4c

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#756]
"As the pain sears through you, your group of arm-like, pointed fox-dicks immediately become fully erect and leak pre-cum liberally from their tips.  four[should be capitalized] thorny tentacles pierce your nipples, and you feel as if someone shot acid into your tits, which immediately begin to swell."

**Comment by ambjoorn94** [comment]
This issue is due to a call of the function
num2Text
instead of
Num2Text
