### ISSUE TITLE
Phoenix Tower quest bugged?

### ISSUE THREAD

**Issue by scar1966** [herp-a-derp/Corruption-of-Champions#771]
I completed the Phoenix tower quest today, but the quest would NOT let me leave! The leave option was missing and Hakam never left with Helia. I was stuck there for over an entire game day.

**Comment by Likethisone** [comment]
I solved this problem (which is also with Lethice's Stronghold) by using a previous version of CoC ( 0.9.0, to be specific). And it works.

**Comment by Gedan** [comment]
Seems to be working fine for me; tested against 0.8.6 and everything is operating in exactly the same manner with my test characters.

Gonna need a save to see this for myself, otherwise, nothing to see here.
