### ISSUE TITLE
CoC_0.9.4c All text missing for both the Onahole and Deluxe Onahole

### ISSUE THREAD

**Issue by commshep12** [herp-a-derp/Corruption-of-Champions#773]
I recently started a new game with the current build and I noticed that anytime I use the onahole it doesn't display any scene at all while the dildo works just fine.

**Comment by ambjoorn94** [comment]
Ah, finally after a few days of searching, I found that all text was cleared before the "Next" button prompt. Making all text appear as if it was never there at all. This can be fixed in a few different ways.
