### ISSUE TITLE
No "Leave" button present after defeating Imp in 0.9.4c

### ISSUE THREAD

**Issue by Dandela** [herp-a-derp/Corruption-of-Champions#774]
After defeating an Imp as a female character, with Lusty Maiden's armor equipped in CoC_0.9.4c , the only opition present is "Female Rape". 

Also, bug isn't present in CoC_0.9.2 .

To reproduce, 

Make female char
Acquire Lusty Maiden Armor (requires at least a D-cup)
Fight and defeat an imp (with >=30 Lust)

**Comment by Dandela** [comment]
Also, bug isn't present in CoC_0.9.2 .

**Comment by Gedan** [comment]
Seems to be working just fine.
