### ISSUE TITLE
"Kiha's Home Cooking" typo. 

### ISSUE THREAD

**Issue by CalCoast** [herp-a-derp/Corruption-of-Champions#776]
During one of Kiha's "hang-out" scenes, you get this: 

"You share a laugh with the pretty dragoness as she grabs a strip of meat and woofs it down.” 

It should be: 

"You share a laugh with the pretty dragoness as she grabs a strip of meat and wolfs it down.”

**Comment by ambjoorn94** [comment]
The pull request hasn't been accepted yet, shouldn't we wait until it's merged before closing issues?

**Comment by CalCoast** [comment]
Sorry, thought it was dealt with.
