### ISSUE TITLE
CoC Local Save files not locatable in Windows 10

### ISSUE THREAD

**Issue by naninaze** [herp-a-derp/Corruption-of-Champions#778]
As simple as it states. I downloaded the newest version of CoC after upgrading to Windows 10 and can not find the save files on my computer at all. Nor can I find them and alter them using the CoC Editor. I have attempted to use the paths I did when using windows 8.1 and they bring up nothing.

**Comment by ambjoorn94** [comment]
Try to do a full search on the drive for "Macromedia"
Since I don't own Windows 10 yet I can't help you much.
Although it would be a great help if we could find out where the files are located

**Comment by naninaze** [comment]
Macromedia does not have any CoC files. All it has is the Core file and a file for Skype.

**Comment by naninaze** [comment]
Ok I found it. Apparently Windows 10 likes to store the file in this directory: C:\Users\Admin\AppData\Local\Google\Chrome\User Data\Profile <#>\Pepper Data\Shockwave Flash\WritableRoot\#SharedObjects\<Numbers>\localhost

**Comment by tmedwards** [comment]
1. This really has nothing to do with CoC.
2. This also really has nothing to do with Windows 10. Chrome's `Pepper` plugin architecture is different from what other browsers are currently using (the old `NPAPI`), so the path to its Flash shared object store is different from other browsers.  In your case, it's possible/probable that Chrome upgraded itself from the old per-user install scheme, which they used to use, to the newer all-users scheme currently in use, which would have changed the path to the store.
3. If by "CoC Editor" you mean CoCEd, then [it has its own issue tracker](https://github.com/tmedwards/CoCEd/issues "https://github.com/tmedwards/CoCEd/issues") which you should create an issue on.
