### ISSUE TITLE
"smooth, rough" skin and gramar errors in 'bauble' Tease - 0.9.4c

### ISSUE THREAD

**Issue by Zeikfried** [herp-a-derp/Corruption-of-Champions#788]
-dashes after "useless" and "shiny" should be removed
-omit "smooth," as player skin descript already contains adjectives
-relevant section:

The clear, warm fluid of your happy excitement trickles down from your loins, polishing your smooth, rough gray skin to a glossy, inviting shine. Retrieving the useless- though shiny- bauble, you hold your pose for just a moment longer, a sly little smile playing across your lips as you wiggle your cheeks one more time before straightening up and turning back around.

**Comment by ambjoorn94** [comment]
"The clear, warm fluid of your happy excitement trickles down from your loins, polishing your " + player.skin() + " to a glossy, inviting shine.  Retrieving the useless- though shiny- bauble, you hold your pose for just a moment longer, a sly little smile playing across your lips as you wiggle your cheeks one more time before straightening up and turning back around."

There is no 'smooth' in this text.

Also got a question:
"Retrieving the useless though shiny bauble, "
or
"Retrieving the useless-though-shiny bauble, "
Which should be used?

**Comment by Zeikfried** [comment]
Then it looks like this is a reappearance of the old skin descript error from "rough gray" shark skin being combined with "smooth" from a smalll black egg.

And the latter hyphenated expression is correct, actually. As would be "useless, though shiny, bauble", which I suspect is what the coder/writer was doing when he had a misfired neuron.

**Comment by ambjoorn94** [comment]
skinTone = "rough gray"
skinAdj = "smooth"

The black eggs (large and not large) both change "rough gray" to "gray".
However, normal shark teeth don't seem to take "smooth" adjective into account, nor even check the adjective.

I think I will change the expression to "useless, though shiny, bauble" since that seems to be what the writer intended. Any objections?

**Comment by Zeikfried** [comment]
I prefer adding a check for 'gray' whereupon the skin doesn't change. Shark teeth should retain most of their proper power (giving the player sharkskin if not present), but not interfere if the PC has modified to 'smooth' sharkskin (since it was probably done by choice).

**Comment by ambjoorn94** [comment]
Done, added a check for gray, also added a check for smooth adjective when changing to gray (or rough gray if not smooth)

Honestly I'm surprised "rough" isn't in the adjective list. Well, I guess people should be able to have "latex, rough gray" or something similar, even though it doesn't sound nice to say it in that order...
