### ISSUE TITLE
Harpy Tower - Kiri Anal "Shift" Typo

### ISSUE THREAD

**Issue by CalCoast** [herp-a-derp/Corruption-of-Champions#798]
When asking Kiri for anal in the Harpy Tower, there's an odd choice of words that could be a typo: 

*"You whip your segmented shaft out of your full platemail and tell Kiri to get on all fours. She grimaces, but does as you ask. You hike up her* ***shift*** *to reveal her large, egg-laying pussy and her tight little pucker."*

*Skirt*, perhaps?

**Comment by ambjoorn94** [comment]
Unfortunately, there is no mention of a skirt anywhere related to Kiri.
Any other suggestions?

**Comment by CalCoast** [comment]
Well, the term "shift" seemed off when used in the manner quoted. Decided to do some research though, and discovered an obscure definition for "shift" I'd never heard of before. 

"A woman's straight, unwaisted dress." 
"A long, loose-fitting undergarment. [Historical.]"

What's she said to wear (if anything)? If nothing at all, perhaps the mention of "hiking" anything up could just be replaced by **spreading**. If she DOES wear clothing, I **suppose** the current term works? Just seems odd to me, as though there were too few contextual clues for that specific type of clothing to bother with that particular word.

**Comment by tmedwards** [comment]
While shifts are largely historical, I wouldn't call it an obscure term, in general; certainly not with respect to the genre CoC inhabits.  A more modern word would be chemise, but again considering the genre, shift is entirely appropriate; especially considering the modern usage of chemise is usually limited to undergarments, in general, and lingerie, specifically.

Hiking is an appropriate verb considering the type of clothing involved (i.e. you don't spread a shift, you raise/hike it up).

Apropos of nothing, the term is still used occasionally around here (south-central US).

**Comment by ambjoorn94** [comment]
From Kiri's "Get Licked" sex scene:
> you urge her on with little pats of the head and shoulders, even reaching down to cup one of her perky breasts beneath her loose shift or stroke one of her great orange wings.

So it does seem like she actually is wearing a **shift**

**Comment by CalCoast** [comment]
TIL a new word.
