### ISSUE TITLE
Katherine's Exam puncuation question. 

### ISSUE THREAD

**Issue by CalCoast** [herp-a-derp/Corruption-of-Champions#800]
*"Urta gives you a big smile as you lead Katherine over to her table. “How’s it going [Champion]?” When Kath sits down she adds, “And who’s this?” in a friendly tone.*

*You explain to Urta how you’ve been training Kath in the hopes of getting her a job in the watch. Urta sips from her mug and listens closely as you go over the training. When you finish Urta says, “You know I could have given you a hand with that love.”*

What's the judgement for commas, generally? All in all, I see **tons** of points where I think there should be commas *(usually addressing commas, as in before saying the Champion's name/nickname)*. 

I'd personally add *three* to Urta's lines in the above, quoted section, and move the first comma in the quoted block *after* the quotation marks. I don't know if these is getting to be too small of issues I'm bringing up or not, but I'm just trying to be helpful.

**Comment by ambjoorn94** [comment]
**Change Nr 1:**
> “How’s it going [Champion]?”

changed to
> “How’s it going, [Champion]?”

**Change Nr 2:**
> “You know I could have given you a hand with that love.”

changed to
> “You know I could have given you a hand with that, love.”

**Change Nr 3:**
> I’m guessing from the look on your face you two have been sleeping together for a while too, hmmm?  Where have you been hiding her [Champion]?

changed to
> I’m guessing from the look on your face, you two have been sleeping together for a while too, hmmm?  Where have you been hiding her, [Champion]?

Any other places that need changing?

**Comment by CalCoast** [comment]
If I'm given free reign to share my opinion on what and how it should be changed, then... 

**Change #4:** 

>When Kath sits down she adds, “And who’s this?” in a friendly tone.

changed to

>When Kath sits down, she adds “And who’s this?” in a friendly tone.

Reason? Better flow, IMO. 

**Change #5:** 

>“You know I could have given you a hand with that love.”

changed to

>“You know, I could have given you a hand with that love.”

Reasoning? In the scene, Urta was trying to lightheartedly clue the Champion in that she could have been of assistance. In its current state, I'd argue that it appears Urta is stating a knowledge claim, as in making a matter-of-fact statement about what the Champion knows.
