### ISSUE TITLE
Declining Frosty's Cupcake-Contract "No" Button

### ISSUE THREAD

**Issue by CalCoast** [herp-a-derp/Corruption-of-Champions#801]
Denying Frosty the cupcake-girl's "free service" request after signing her contract didn't take away all the buttons from the previous choice. The "no" button remains on-screen even after the rest disappear. It doesn't have any sort of effect after initially clicking it, and has no reason to be there. 

*"You’re too busy right now, so you deny the free service. “Okeydokey, see you around [Player].” Frosty does a twirl on one foot and runs back to her stand. Such a nice girl."*

*(Also, should there be a comma just before "[Player]" in the above quote?)*

**Comment by ambjoorn94** [comment]
Discovered missing 
> menu();

call. It has been hunted down and placed where it belongs.
