### ISSUE TITLE
corrupted jojo has no options?

### ISSUE THREAD

**Issue by mintywitch** [herp-a-derp/Corruption-of-Champions#803]
I corrupted the mouse monk entirely, bringing him in as a slave at my camp. When I want to use him, there are no options. Later, I found the salon and did that thing, then I went to my camp and clicked through to Jojo. His only listed option was for the salon, I can't remember the exact words. Is this supposed to happen?

**Comment by ambjoorn94** [comment]
List of requirements for Corrupt Jojo buttons:
* Sex: Lust is 33 or more AND not genderless
* TentacleSex: Lust is 33 or more AND Jojo has tentacle cock
* Milk Him: Cockmilker at Whitney's farm
* TentacleMilk: Cockmilker at Whitney's farm, has cockmilked him at least once before AND Jojo has tentacle cock
* HairCare: Has met Lynette
* Lay Eggs: Has Bee ovipositor

And then 2 choices for if he should work at farm or not, requires that you've started corrupting Whitney's farm

If you meet the requirements, yet still don't see the button. Comment here again. If this fixes your problem, you may close the issue.
