### ISSUE TITLE
Question regarding implementation of new code.

### ISSUE THREAD

**Issue by Korvas** [herp-a-derp/Corruption-of-Champions#804]
I recently started adding in new things to CoC's code, mostly to change the theme and setting for my own purposes. I have so far successfully implemented changes for the opening, a new perk, some descriptions, etc. But then I went to add in new body types and cock types. Now, the first one I added, FACE_HEDGEHOG and all the other parts assosiated, including lower body, hair, cock, and ears, are all reading as correct in the editor, but everything else for body type that I added is returning the error,
Access of undefined property.

Could someone point me in the right direction of where I need to go to complete this code because I seem to have forgotten. 

Also, on an unrelated matter, could I write and add a corruption path for Raphael to the game, since it seems the character has been abandoned. Do I need to get the original creator's permission first?

**Comment by Gedan** [comment]
Pretty much best bet is go speak to Kitteh on the forums. Unless we get a PR that's literally perfect and just requires a little bit of eyeball time then it's unlikely we're gonna do anything with it in an official capacity. Gotta wrap this up at some point, right?
