### ISSUE TITLE
Can't find the image pack?

### ISSUE THREAD

**Issue by TreePuncher9501** [herp-a-derp/Corruption-of-Champions#816]
This is less of an issue and more of a question I need assistance with. I cannot seem to find the image pack on Fenoxo's website, nor the wiki, so I ask, where might I be able to find/download it?

**Comment by Gedan** [comment]
https://fenoxo.com/forum/index.php?/topic/36-hn0s-custom-image-pack-version-5/#comment-182

The "official" one only had a handful of images and was only intended as a demonstration of how to set one up.

**Comment by Fenoxo** [comment]
Woulda been better if the artist that showed up and said he was gonna do it
did more than three characters.
