### ISSUE TITLE
in Bog / LizanRogueScene

### ISSUE THREAD

**Issue by Fergusson951** [herp-a-derp/Corruption-of-Champions#845]
ERROR: cockDescript Called But No Cock Present (in Bog / LizanRogueScene - [cock] before 'At your instance he picks up the pace') ___called in female\male fuction

**Comment by Fergusson951** [comment]
I been waiting so long... and I renew the Image Pack 1.4.7 with new and fresh pictures, here my compilation with sample: https://yadi.sk/d/WlI0m6Ja3KrXiX / Sample is a single (file.as), what includes examples how arrange the (images.showImage) in the middle of the text / Many of absolutely new pictures not tied with fuction to game (badends, items (of rathazul), and some others...), but they adapted by their stylistic names! Because I use your project in russian translated version - you may see some rus words in my some-rus-version, just a little... So... let's taste it!
- 1. arranged the badend for DemonPack in Desert
- 2. included the pic-scenes (LizanRogue, Phouka (Faerie), Froggirl, WildHunt (ErlKing), Oasis (DemonPack)) - many female ver, little male ver
- 3. dungeon pics reloaded
- 4. (monster-) pics reloaded
- 5. included pic-scenes (GangBang - centaur(2pics) / not_centaur (2pics))
- 6. reloaded location pics...
+ working GreenSlime Full Image Pack (10pics)
+ save (unlocked bog, mountain, lake and some other locations)
Compilation 'by my style/taste' - classic, some furry, less anthro, some beastiality, romantic... and hardcore badends. That's all, for now...

**Comment by Kitteh6660** [comment]
Wrong branch, please take it to different fork.

**Comment by Fergusson951** [comment]
its an old info - just forget it
